---
title: "delete_var_smmothing"
author: "XSun"
date: "2023-04-14"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

# 1kb

## A - G

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=10}

data <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/data_processed/chr22/chr22.expobs.SNV.1kb.ag.bed", fill = T)
data <- data[complete.cases(data$SNV_exp),]
data$SNV_obs[data$SNV_obs ==0] <- 0.5

data$Mb <- data$start / 1000000

data$randeff <- data$SNV_obs/data$SNV_exp
data$log_randeff <- log(data$randeff)

smooth <- smash.gaus(data$log_randeff,joint = T)
data$var <- smooth$var.res
data$randeff_sm_diff_var <- smooth$mu.res
  
const_var <- sd_estimate_gasser_etal(data$log_randeff)
print(paste0("the current constant variance is ", const_var ))

ggplot(data, aes(x = Mb, y = var)) +
  geom_point(size=0.2) +
  labs(x = "Genomic position(MB)", y = "Variance") +
  geom_line(aes(x = data$Mb, y = const_var), color = "red",size=0.2) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

print("the log(random effect) using default setting:")
ggplot(data, aes(x = Mb, y = log_randeff)) +
  geom_point(size=0.2) +
  geom_line(aes(x = Mb, y = randeff_sm_diff_var), color = "red",size=0.2) +
  labs(x = "Genomic position(MB)", y = "log(Random Effect)") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

print("the log(random effect) using constant variance:")
data$lgre_const <- smash.gaus(data$log_randeff,sigma = const_var)
ggplot(data, aes(x = Mb, y = log_randeff)) +
  geom_point(size=0.2) +
  geom_line(aes(x = Mb, y = lgre_const), color = "red",size=0.2) +
  labs(x = "Genomic position(MB)", y = "log(Random Effect)") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))


```


## A - C

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=10}

data <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/data_processed/chr22/chr22.expobs.SNV.1kb.ac.bed", fill = T)
data <- data[complete.cases(data$SNV_exp),]
data$SNV_obs[data$SNV_obs ==0] <- 0.5

data$Mb <- data$start / 1000000

data$randeff <- data$SNV_obs/data$SNV_exp
data$log_randeff <- log(data$randeff)

smooth <- smash.gaus(data$log_randeff,joint = T)
data$var <- smooth$var.res
data$randeff_sm_diff_var <- smooth$mu.res
  
const_var <- sd_estimate_gasser_etal(data$log_randeff)
print(paste0("the current constant variance is ", const_var ))

ggplot(data, aes(x = Mb, y = var)) +
  geom_point(size=0.2) +
  labs(x = "Genomic position(MB)", y = "Variance") +
  geom_line(aes(x = data$Mb, y = const_var), color = "red",size=0.2) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

print("the log(random effect) using default setting:")
ggplot(data, aes(x = Mb, y = log_randeff)) +
  geom_point(size=0.2) +
  geom_line(aes(x = Mb, y = randeff_sm_diff_var), color = "red",size=0.2) +
  labs(x = "Genomic position(MB)", y = "log(Random Effect)") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

print("the log(random effect) using constant variance:")
data$lgre_const <- smash.gaus(data$log_randeff,sigma = const_var)
ggplot(data, aes(x = Mb, y = log_randeff)) +
  geom_point(size=0.2) +
  geom_line(aes(x = Mb, y = lgre_const), color = "red",size=0.2) +
  labs(x = "Genomic position(MB)", y = "log(Random Effect)") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))


```

## A - T

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=10}

data <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/data_processed/chr22/chr22.expobs.SNV.1kb.at.bed", fill = T)
data <- data[complete.cases(data$SNV_exp),]
data$SNV_obs[data$SNV_obs ==0] <- 0.5

data$Mb <- data$start / 1000000

data$randeff <- data$SNV_obs/data$SNV_exp
data$log_randeff <- log(data$randeff)

smooth <- smash.gaus(data$log_randeff,joint = T)
data$var <- smooth$var.res
data$randeff_sm_diff_var <- smooth$mu.res
  
const_var <- sd_estimate_gasser_etal(data$log_randeff)
print(paste0("the current constant variance is ", const_var ))

ggplot(data, aes(x = Mb, y = var)) +
  geom_point(size=0.2) +
  labs(x = "Genomic position(MB)", y = "Variance") +
  geom_line(aes(x = data$Mb, y = const_var), color = "red",size=0.2) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

print("the log(random effect) using default setting:")
ggplot(data, aes(x = Mb, y = log_randeff)) +
  geom_point(size=0.2) +
  geom_line(aes(x = Mb, y = randeff_sm_diff_var), color = "red",size=0.2) +
  labs(x = "Genomic position(MB)", y = "log(Random Effect)") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

print("the log(random effect) using constant variance:")
data$lgre_const <- smash.gaus(data$log_randeff,sigma = const_var)
ggplot(data, aes(x = Mb, y = log_randeff)) +
  geom_point(size=0.2) +
  geom_line(aes(x = Mb, y = lgre_const), color = "red",size=0.2) +
  labs(x = "Genomic position(MB)", y = "log(Random Effect)") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))


```

## C - A

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=10}

data <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/data_processed/chr22/chr22.expobs.SNV.1kb.ca.bed", fill = T)
data <- data[complete.cases(data$SNV_exp),]
data$SNV_obs[data$SNV_obs ==0] <- 0.5

data$Mb <- data$start / 1000000

data$randeff <- data$SNV_obs/data$SNV_exp
data$log_randeff <- log(data$randeff)

smooth <- smash.gaus(data$log_randeff,joint = T)
data$var <- smooth$var.res
data$randeff_sm_diff_var <- smooth$mu.res
  
const_var <- sd_estimate_gasser_etal(data$log_randeff)
print(paste0("the current constant variance is ", const_var ))

ggplot(data, aes(x = Mb, y = var)) +
  geom_point(size=0.2) +
  labs(x = "Genomic position(MB)", y = "Variance") +
  geom_line(aes(x = data$Mb, y = const_var), color = "red",size=0.2) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

print("the log(random effect) using default setting:")
ggplot(data, aes(x = Mb, y = log_randeff)) +
  geom_point(size=0.2) +
  geom_line(aes(x = Mb, y = randeff_sm_diff_var), color = "red",size=0.2) +
  labs(x = "Genomic position(MB)", y = "log(Random Effect)") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

print("the log(random effect) using constant variance:")
data$lgre_const <- smash.gaus(data$log_randeff,sigma = const_var)
ggplot(data, aes(x = Mb, y = log_randeff)) +
  geom_point(size=0.2) +
  geom_line(aes(x = Mb, y = lgre_const), color = "red",size=0.2) +
  labs(x = "Genomic position(MB)", y = "log(Random Effect)") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))


```


## C - G

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=10}

data <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/data_processed/chr22/chr22.expobs.SNV.1kb.cg.bed", fill = T)
data <- data[complete.cases(data$SNV_exp),]
data$SNV_obs[data$SNV_obs ==0] <- 0.5

data$Mb <- data$start / 1000000

data$randeff <- data$SNV_obs/data$SNV_exp
data$log_randeff <- log(data$randeff)

smooth <- smash.gaus(data$log_randeff,joint = T)
data$var <- smooth$var.res
data$randeff_sm_diff_var <- smooth$mu.res
  
const_var <- sd_estimate_gasser_etal(data$log_randeff)
print(paste0("the current constant variance is ", const_var ))

ggplot(data, aes(x = Mb, y = var)) +
  geom_point(size=0.2) +
  labs(x = "Genomic position(MB)", y = "Variance") +
  geom_line(aes(x = data$Mb, y = const_var), color = "red",size=0.2) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

print("the log(random effect) using default setting:")
ggplot(data, aes(x = Mb, y = log_randeff)) +
  geom_point(size=0.2) +
  geom_line(aes(x = Mb, y = randeff_sm_diff_var), color = "red",size=0.2) +
  labs(x = "Genomic position(MB)", y = "log(Random Effect)") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

print("the log(random effect) using constant variance:")
data$lgre_const <- smash.gaus(data$log_randeff,sigma = const_var)
ggplot(data, aes(x = Mb, y = log_randeff)) +
  geom_point(size=0.2) +
  geom_line(aes(x = Mb, y = lgre_const), color = "red",size=0.2) +
  labs(x = "Genomic position(MB)", y = "log(Random Effect)") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))


```


## C - T

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=10}

data <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/data_processed/chr22/chr22.expobs.SNV.1kb.ct.bed", fill = T)
data <- data[complete.cases(data$SNV_exp),]
data$SNV_obs[data$SNV_obs ==0] <- 0.5

data$Mb <- data$start / 1000000

data$randeff <- data$SNV_obs/data$SNV_exp
data$log_randeff <- log(data$randeff)

smooth <- smash.gaus(data$log_randeff,joint = T)
data$var <- smooth$var.res
data$randeff_sm_diff_var <- smooth$mu.res
  
const_var <- sd_estimate_gasser_etal(data$log_randeff)
print(paste0("the current constant variance is ", const_var ))

ggplot(data, aes(x = Mb, y = var)) +
  geom_point(size=0.2) +
  labs(x = "Genomic position(MB)", y = "Variance") +
  geom_line(aes(x = data$Mb, y = const_var), color = "red",size=0.2) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

print("the log(random effect) using default setting:")
ggplot(data, aes(x = Mb, y = log_randeff)) +
  geom_point(size=0.2) +
  geom_line(aes(x = Mb, y = randeff_sm_diff_var), color = "red",size=0.2) +
  labs(x = "Genomic position(MB)", y = "log(Random Effect)") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

print("the log(random effect) using constant variance:")
data$lgre_const <- smash.gaus(data$log_randeff,sigma = const_var)
ggplot(data, aes(x = Mb, y = log_randeff)) +
  geom_point(size=0.2) +
  geom_line(aes(x = Mb, y = lgre_const), color = "red",size=0.2) +
  labs(x = "Genomic position(MB)", y = "log(Random Effect)") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))


```


# 10kb

## A - G

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=10}

data <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/data_processed/chr22/chr22.expobs.SNV.10kb.ag.bed", fill = T)
data <- data[complete.cases(data$SNV_exp),]
data$SNV_obs[data$SNV_obs ==0] <- 0.5

data$Mb <- data$start / 1000000

data$randeff <- data$SNV_obs/data$SNV_exp
data$log_randeff <- log(data$randeff)

smooth <- smash.gaus(data$log_randeff,joint = T)
data$var <- smooth$var.res
data$randeff_sm_diff_var <- smooth$mu.res
  
const_var <- sd_estimate_gasser_etal(data$log_randeff)
print(paste0("the current constant variance is ", const_var ))

ggplot(data, aes(x = Mb, y = var)) +
  geom_point(size=0.2) +
  labs(x = "Genomic position(MB)", y = "Variance") +
  geom_line(aes(x = data$Mb, y = const_var), color = "red",size=0.2) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

print("the log(random effect) using default setting:")
ggplot(data, aes(x = Mb, y = log_randeff)) +
  geom_point(size=0.2) +
  geom_line(aes(x = Mb, y = randeff_sm_diff_var), color = "red",size=0.2) +
  labs(x = "Genomic position(MB)", y = "log(Random Effect)") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

print("the log(random effect) using constant variance:")
data$lgre_const <- smash.gaus(data$log_randeff,sigma = const_var)
ggplot(data, aes(x = Mb, y = log_randeff)) +
  geom_point(size=0.2) +
  geom_line(aes(x = Mb, y = lgre_const), color = "red",size=0.2) +
  labs(x = "Genomic position(MB)", y = "log(Random Effect)") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))


```


## A - C

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=10}

data <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/data_processed/chr22/chr22.expobs.SNV.10kb.ac.bed", fill = T)
data <- data[complete.cases(data$SNV_exp),]
data$SNV_obs[data$SNV_obs ==0] <- 0.5

data$Mb <- data$start / 1000000

data$randeff <- data$SNV_obs/data$SNV_exp
data$log_randeff <- log(data$randeff)

smooth <- smash.gaus(data$log_randeff,joint = T)
data$var <- smooth$var.res
data$randeff_sm_diff_var <- smooth$mu.res
  
const_var <- sd_estimate_gasser_etal(data$log_randeff)
print(paste0("the current constant variance is ", const_var ))

ggplot(data, aes(x = Mb, y = var)) +
  geom_point(size=0.2) +
  labs(x = "Genomic position(MB)", y = "Variance") +
  geom_line(aes(x = data$Mb, y = const_var), color = "red",size=0.2) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

print("the log(random effect) using default setting:")
ggplot(data, aes(x = Mb, y = log_randeff)) +
  geom_point(size=0.2) +
  geom_line(aes(x = Mb, y = randeff_sm_diff_var), color = "red",size=0.2) +
  labs(x = "Genomic position(MB)", y = "log(Random Effect)") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

print("the log(random effect) using constant variance:")
data$lgre_const <- smash.gaus(data$log_randeff,sigma = const_var)
ggplot(data, aes(x = Mb, y = log_randeff)) +
  geom_point(size=0.2) +
  geom_line(aes(x = Mb, y = lgre_const), color = "red",size=0.2) +
  labs(x = "Genomic position(MB)", y = "log(Random Effect)") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))


```

## A - T

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=10}

data <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/data_processed/chr22/chr22.expobs.SNV.10kb.at.bed", fill = T)
data <- data[complete.cases(data$SNV_exp),]
data$SNV_obs[data$SNV_obs ==0] <- 0.5

data$Mb <- data$start / 1000000

data$randeff <- data$SNV_obs/data$SNV_exp
data$log_randeff <- log(data$randeff)

smooth <- smash.gaus(data$log_randeff,joint = T)
data$var <- smooth$var.res
data$randeff_sm_diff_var <- smooth$mu.res
  
const_var <- sd_estimate_gasser_etal(data$log_randeff)
print(paste0("the current constant variance is ", const_var ))

ggplot(data, aes(x = Mb, y = var)) +
  geom_point(size=0.2) +
  labs(x = "Genomic position(MB)", y = "Variance") +
  geom_line(aes(x = data$Mb, y = const_var), color = "red",size=0.2) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

print("the log(random effect) using default setting:")
ggplot(data, aes(x = Mb, y = log_randeff)) +
  geom_point(size=0.2) +
  geom_line(aes(x = Mb, y = randeff_sm_diff_var), color = "red",size=0.2) +
  labs(x = "Genomic position(MB)", y = "log(Random Effect)") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

print("the log(random effect) using constant variance:")
data$lgre_const <- smash.gaus(data$log_randeff,sigma = const_var)
ggplot(data, aes(x = Mb, y = log_randeff)) +
  geom_point(size=0.2) +
  geom_line(aes(x = Mb, y = lgre_const), color = "red",size=0.2) +
  labs(x = "Genomic position(MB)", y = "log(Random Effect)") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))


```

## C - A

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=10}

data <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/data_processed/chr22/chr22.expobs.SNV.10kb.ca.bed", fill = T)
data <- data[complete.cases(data$SNV_exp),]
data$SNV_obs[data$SNV_obs ==0] <- 0.5

data$Mb <- data$start / 1000000

data$randeff <- data$SNV_obs/data$SNV_exp
data$log_randeff <- log(data$randeff)

smooth <- smash.gaus(data$log_randeff,joint = T)
data$var <- smooth$var.res
data$randeff_sm_diff_var <- smooth$mu.res
  
const_var <- sd_estimate_gasser_etal(data$log_randeff)
print(paste0("the current constant variance is ", const_var ))

ggplot(data, aes(x = Mb, y = var)) +
  geom_point(size=0.2) +
  labs(x = "Genomic position(MB)", y = "Variance") +
  geom_line(aes(x = data$Mb, y = const_var), color = "red",size=0.2) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

print("the log(random effect) using default setting:")
ggplot(data, aes(x = Mb, y = log_randeff)) +
  geom_point(size=0.2) +
  geom_line(aes(x = Mb, y = randeff_sm_diff_var), color = "red",size=0.2) +
  labs(x = "Genomic position(MB)", y = "log(Random Effect)") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

print("the log(random effect) using constant variance:")
data$lgre_const <- smash.gaus(data$log_randeff,sigma = const_var)
ggplot(data, aes(x = Mb, y = log_randeff)) +
  geom_point(size=0.2) +
  geom_line(aes(x = Mb, y = lgre_const), color = "red",size=0.2) +
  labs(x = "Genomic position(MB)", y = "log(Random Effect)") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))


```


## C - G

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=10}

data <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/data_processed/chr22/chr22.expobs.SNV.10kb.cg.bed", fill = T)
data <- data[complete.cases(data$SNV_exp),]
data$SNV_obs[data$SNV_obs ==0] <- 0.5

data$Mb <- data$start / 1000000

data$randeff <- data$SNV_obs/data$SNV_exp
data$log_randeff <- log(data$randeff)

smooth <- smash.gaus(data$log_randeff,joint = T)
data$var <- smooth$var.res
data$randeff_sm_diff_var <- smooth$mu.res
  
const_var <- sd_estimate_gasser_etal(data$log_randeff)
print(paste0("the current constant variance is ", const_var ))

ggplot(data, aes(x = Mb, y = var)) +
  geom_point(size=0.2) +
  labs(x = "Genomic position(MB)", y = "Variance") +
  geom_line(aes(x = data$Mb, y = const_var), color = "red",size=0.2) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

print("the log(random effect) using default setting:")
ggplot(data, aes(x = Mb, y = log_randeff)) +
  geom_point(size=0.2) +
  geom_line(aes(x = Mb, y = randeff_sm_diff_var), color = "red",size=0.2) +
  labs(x = "Genomic position(MB)", y = "log(Random Effect)") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

print("the log(random effect) using constant variance:")
data$lgre_const <- smash.gaus(data$log_randeff,sigma = const_var)
ggplot(data, aes(x = Mb, y = log_randeff)) +
  geom_point(size=0.2) +
  geom_line(aes(x = Mb, y = lgre_const), color = "red",size=0.2) +
  labs(x = "Genomic position(MB)", y = "log(Random Effect)") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))


```


## C - T

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=10}

data <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/data_processed/chr22/chr22.expobs.SNV.10kb.ct.bed", fill = T)
data <- data[complete.cases(data$SNV_exp),]
data$SNV_obs[data$SNV_obs ==0] <- 0.5

data$Mb <- data$start / 1000000

data$randeff <- data$SNV_obs/data$SNV_exp
data$log_randeff <- log(data$randeff)

smooth <- smash.gaus(data$log_randeff,joint = T)
data$var <- smooth$var.res
data$randeff_sm_diff_var <- smooth$mu.res
  
const_var <- sd_estimate_gasser_etal(data$log_randeff)
print(paste0("the current constant variance is ", const_var ))

ggplot(data, aes(x = Mb, y = var)) +
  geom_point(size=0.2) +
  labs(x = "Genomic position(MB)", y = "Variance") +
  geom_line(aes(x = data$Mb, y = const_var), color = "red",size=0.2) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

print("the log(random effect) using default setting:")
ggplot(data, aes(x = Mb, y = log_randeff)) +
  geom_point(size=0.2) +
  geom_line(aes(x = Mb, y = randeff_sm_diff_var), color = "red",size=0.2) +
  labs(x = "Genomic position(MB)", y = "log(Random Effect)") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

print("the log(random effect) using constant variance:")
data$lgre_const <- smash.gaus(data$log_randeff,sigma = const_var)
ggplot(data, aes(x = Mb, y = log_randeff)) +
  geom_point(size=0.2) +
  geom_line(aes(x = Mb, y = lgre_const), color = "red",size=0.2) +
  labs(x = "Genomic position(MB)", y = "log(Random Effect)") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))


```

