---
title: "Debug"
author: "XSun"
date: "2023-04-08"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---


```{r echo=FALSE, message=FALSE, warning=FALSE}
suppressMessages(library(ggplot2))
suppressMessages(library(smashr))
suppressMessages(library(gridExtra))
```

## All mutation types  -- 1kb window

```{r echo=FALSE, message=FALSE, warning=FALSE}
load("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/data_processed/chr22/smash_1kb_pseudo05_wholewindow.rdata")
data$Mb <- data$start / 1000000
data_save <- data
```

In the earlier setting, we smoothed the random effects for all 36,873 windows at the same time. 

For 31~32Mb region, we have: 

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=10}
data <- data_save
data <- data[data$Mb >31 &data$Mb <32, ]
ggplot(data, aes(x = Mb, y = randeff)) +
  geom_point(size=0.2) +
  geom_line(aes(x = Mb, y = randeff_sm), color = "red",size=0.2) +
  labs(x = "Genomic position(MB)", y = "Random Effect") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

```

But if we cut the 31~32 Mb region first, and then just smooth this region, we have: 

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=10}
data <- data_save
data <- data[data$Mb >31 &data$Mb <32, ]
data$randeff_sm <- smash.gaus(data$randeff)
ggplot(data, aes(x = Mb, y = randeff)) +
  geom_point(size=0.2) +
  geom_line(aes(x = Mb, y = randeff_sm), color = "red",size=0.2) +
  labs(x = "Genomic position(MB)", y = "Random Effect") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

```

