---
title: "De novo mutations"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
editor_options:
  chunk_output_type: console
---


Data Overview

- SSC de novo mutations from An et al. Science 2018 contains 7,608 samples in 1,902 autism spectrum disorder (ASD) families, identifying 255,106 de novo mutations in total, 233,954 of them are de novo SNVs.

- SSC de novo mutations from Trost et al. Cell 2022 contains 9,205 samples, identifying 326,669 de novo SNVs (these variants were not used in their TADA analysis).

- Trost et al. Cell 2022 also provides a collection of 167,760 de novo mutations from MSSNG, SPARK, and ASC. 145,237 of them are de novo SNV (these variants were used in their TADA analysis). 

| data set    | trios | cases | control | # of de novo mutations |
|-------------|-------|-------|---------|------------------------|
| ASC         | 6430  | 5556  | 8809    | 15772  [source](https://www.sciencedirect.com/science/article/pii/S0092867419313984)|
| MSSNG       | 3586  | -     | -       | 126788                 |
| SPARK pilot | 465   | -     | -       | 615    [source](https://www.nature.com/articles/s41525-019-0093-8)                |
| SPARK WES 1 | 6577  | -     | -       | 19825  [source](https://www.sciencedirect.com/science/article/pii/S0896627318300187?via%3Dihub)|
| SPARK WES 2 | 2167  | -     | -       | 4760   [source](https://www.sciencedirect.com/science/article/pii/S0896627318300187?via%3Dihub)|

The MSSNG contains 5,100 individuals with ASD and 6,212 non-ASD parents and siblings (total n = 11,312).


# 1. An et al. Science 2018


## Data calibration 

- [Calibrating with Roulette -- SSC](https://xsun1229.github.io/mutation_rate/denovo_rl_an_calibration.html)


# 2. Trost et al. Cell 2022 

## Data calibration 

- [Calibrating with Roulette --  MSSNG, SPARK, and ASC](https://xsun1229.github.io/mutation_rate/denovo_rl_trost_calibration.html)


- [Calibrating with Roulette --  SSC](https://xsun1229.github.io/mutation_rate/denovo_rl_ssc_trost_calibration.html)



# 3. Simons Simplex Collection (Shengtong's collection)

## Data calibration 

- [Calibrating Simon's de novo data with Roulette](https://xsun1229.github.io/mutation_rate/denovo_rl_simno_calibration.html)

- [Cross Validation without smoothing](https://xsun1229.github.io/mutation_rate/denovo_cv_wo_smoothing.html)


## Poisson Model

Cross Validation 

- [Using the first 90% base pairs as training set](https://xsun1229.github.io/mutation_rate/denovo_pois_traintest.html)

Results analysis

- [Plots - Observed & Estimated across all windows](https://xsun1229.github.io/mutation_rate/denovo_pois_allwindows.html)


## Gaussian Model

Cross Validation 

- [Using the first 90% base pairs as training set](https://xsun1229.github.io/mutation_rate/denovo_gaus_traintest.html)

Results analysis

- [Plots - Observed & Estimated across all windows](https://xsun1229.github.io/mutation_rate/denovo_gaus_allwindows.html)


