---
title: "Plots - Observed & Estimated (Gaussian Model)"
author: "XSun"
date: "2023-07-06"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
suppressMessages(library(ggplot2))
suppressMessages(library(gridExtra))
suppressMessages(library(data.table))
```


# 10kb

## chr1 

### all 6 mutation types


```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=10}
file_dat <- paste0("/project/xinhe/xsun/mutation_rate/3.de_novo/results/per_chr/chr1/gaus_10kb_pseudo0005_wholewindow.rdata")
load(file_dat)
colnames(data)[2] <- "exp"

data$Mb <- data$start / 1000000

data$log_randeff <- log(data$obs/data$exp)
data$obs_randeff <- data$exp*data$randeff_sm
data_save <- data

# ggplot(data, aes(x = Mb, y = var)) +
#   geom_point(size=0.2) +
#   labs(x = "Genomic position(MB)", y = "Variance") +
#   theme_bw() +
#   theme(plot.title = element_text(hjust = 0.5))

print("the log(random effect)")
print("red line: smoothed log random effects")
ggplot(data, aes(x = Mb, y = log_randeff)) +
  geom_point(size=0.2) +
  geom_line(aes(x = Mb, y = mean_lgre), color = "red",size=0.2) +
  labs(x = "Genomic position(MB)", y = "log(Random Effect)") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

print("red line: smoothed observed mutation count")
ggplot(data, aes(x = Mb, y = obs)) +
  geom_point(size=0.2) +
  scale_x_continuous(name = "Genomic position (Mb)") +
  ylab("# of de novo muts/window -- poisson") +
  geom_line(aes(x = Mb, y = obs_randeff), data = data, color = "red",size=0.2) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

```


## chr22 

### all 6 mutation types


```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=10}

file_dat <- paste0("/project/xinhe/xsun/mutation_rate/3.de_novo/results/per_chr/chr22/gaus_10kb_pseudo0005_wholewindow.rdata")
load(file_dat)
colnames(data)[2] <- "exp"

data$Mb <- data$start / 1000000

data$log_randeff <- log(data$obs/data$exp)
data$obs_randeff <- data$exp*data$randeff_sm
data_save <- data

# ggplot(data, aes(x = Mb, y = var)) +
#   geom_point(size=0.2) +
#   labs(x = "Genomic position(MB)", y = "Variance") +
#   theme_bw() +
#   theme(plot.title = element_text(hjust = 0.5))

print("the log(random effect)")
print("red line: smoothed log random effects")
ggplot(data, aes(x = Mb, y = log_randeff)) +
  geom_point(size=0.2) +
  geom_line(aes(x = Mb, y = mean_lgre), color = "red",size=0.2) +
  labs(x = "Genomic position(MB)", y = "log(Random Effect)") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

print("red line: smoothed observed mutation count")
ggplot(data, aes(x = Mb, y = obs)) +
  geom_point(size=0.2) +
  scale_x_continuous(name = "Genomic position (Mb)") +
  ylab("# of de novo muts/window -- poisson") +
  geom_line(aes(x = Mb, y = obs_randeff), data = data, color = "red",size=0.2) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

```


## chr22 

### all 6 mutation types


```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=10}

maxiter <- 30
print(paste0("iteration = ", maxiter))

file_dat <- paste0("/project/xinhe/xsun/mutation_rate/3.de_novo/results/per_chr/chr22/gaus_10kb_pseudo0005_wholewindow.rdata")
load(file_dat)
colnames(data)[2] <- "exp"

data$Mb <- data$start / 1000000

data$log_randeff <- log(data$obs/data$exp)
data$obs_randeff <- data$exp*data$randeff_sm
data_save <- data

# ggplot(data, aes(x = Mb, y = var)) +
#   geom_point(size=0.2) +
#   labs(x = "Genomic position(MB)", y = "Variance") +
#   theme_bw() +
#   theme(plot.title = element_text(hjust = 0.5))

print("the log(random effect)")
print("red line: smoothed log random effects")
ggplot(data, aes(x = Mb, y = log_randeff)) +
  geom_point(size=0.2) +
  geom_line(aes(x = Mb, y = mean_lgre), color = "red",size=0.2) +
  labs(x = "Genomic position(MB)", y = "log(Random Effect)") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

print("red line: smoothed observed mutation count")
ggplot(data, aes(x = Mb, y = obs)) +
  geom_point(size=0.2) +
  scale_x_continuous(name = "Genomic position (Mb)") +
  ylab("# of de novo muts/window -- poisson") +
  geom_line(aes(x = Mb, y = obs_randeff), data = data, color = "red",size=0.2) +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

```