---
title: "Spatial & Non-spatial for real data"
author: "XSun"
date: "2023-10-12"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r echo=F,message=FALSE}
library(ggplot2)
library(gridExtra)
library(data.table)
```

We fit the spatial model first then the non-spatial model.

# SSC -- fitting using the whole window

## chr1 

### 10kb

```{r echo=F, message=FALSE, warning=FALSE, fig.width=12, fig.height=5}

load("/project/xinhe/xsun/mutation_rate/8.denovo_sns/results/sns_chr1_10kb_ssc.rdata")
data$randeff_final <- data$randeff_spatial_only * data$randeff_nonspatial_residual

ggplot(data, aes(x =  pos)) +
  geom_line(aes(y = randeff, color = "realdata"), alpha = 0.5) +
  geom_line(aes(y = randeff_spatial_only, color = "Spatial-only")) +
  geom_line(aes(y = randeff_final, color = "spatial&non-spatial"), alpha = 0.5) +
  geom_line(aes(y = randeff_nonspatial_only, color = "Non-spatial only"), alpha = 0.6) +
  labs(x = "Mb",
       y = "random effects") +
  scale_color_manual(name = "Group", 
                     values = c("realdata" = "blue", "Spatial-only" = "red", 
                                "spatial&non-spatial" = "brown", "Non-spatial only" = "green"), 
                     labels = c("obs/exp from real data", "Spatial-only", "spatial&non-spatial", "Non-spatial only")) +
  theme_minimal()


print("spatial only")

fit1 <- lm( randeff_spatial_only ~randeff + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_spatial_only)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - Spatial",
       title = "spatial only") +
  theme_minimal()

print("non-spatial only")
print(sprintf("alpha = %s",alpha_nonspatial_only))
fit1 <- lm( randeff_nonspatial_only ~randeff + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_nonspatial_only)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - non-spatial",
       title = "non-spatial only") +
  theme_minimal()


print("sptial & non-spatial ")
print(sprintf("alpha_non-spatial = %s",alpha_residual))
print("the final estimated random effects = random effects_NS * random effects_S ")


fit1 <- lm( randeff_final ~ randeff+ 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_final)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - - NS * S",
       title = "sptial & non-spatial") +
  theme_minimal()



```







### 30kb

```{r echo=F, message=FALSE, warning=FALSE, fig.width=12, fig.height=5}

load("/project/xinhe/xsun/mutation_rate/8.denovo_sns/results/sns_chr1_30kb_ssc.rdata")
data$randeff_final <- data$randeff_spatial_only * data$randeff_nonspatial_residual

ggplot(data, aes(x =  pos)) +
  geom_line(aes(y = randeff, color = "realdata"), alpha = 0.5) +
  geom_line(aes(y = randeff_spatial_only, color = "Spatial-only")) +
  geom_line(aes(y = randeff_final, color = "spatial&non-spatial"), alpha = 0.5) +
  geom_line(aes(y = randeff_nonspatial_only, color = "Non-spatial only"), alpha = 0.6) +
  labs(x = "Mb",
       y = "random effects") +
  scale_color_manual(name = "Group", 
                     values = c("realdata" = "blue", "Spatial-only" = "red", 
                                "spatial&non-spatial" = "brown", "Non-spatial only" = "green"), 
                     labels = c("obs/exp from real data", "Spatial-only", "spatial&non-spatial", "Non-spatial only")) +
  theme_minimal()


print("spatial only")

fit1 <- lm( randeff_spatial_only ~randeff + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_spatial_only)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - Spatial",
       title = "spatial only") +
  theme_minimal()

print("non-spatial only")
print(sprintf("alpha = %s",alpha_nonspatial_only))
fit1 <- lm( randeff_nonspatial_only ~randeff + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_nonspatial_only)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - non-spatial",
       title = "non-spatial only") +
  theme_minimal()


print("sptial & non-spatial ")
print(sprintf("alpha_non-spatial = %s",alpha_residual))
print("the final estimated random effects = random effects_NS * random effects_S ")


fit1 <- lm( randeff_final ~ randeff+ 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_final)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - - NS * S",
       title = "sptial & non-spatial") +
  theme_minimal()



```








### 50kb

```{r echo=F, message=FALSE, warning=FALSE, fig.width=12, fig.height=5}

load("/project/xinhe/xsun/mutation_rate/8.denovo_sns/results/sns_chr1_50kb_ssc.rdata")
data$randeff_final <- data$randeff_spatial_only * data$randeff_nonspatial_residual

ggplot(data, aes(x =  pos)) +
  geom_line(aes(y = randeff, color = "realdata"), alpha = 0.5) +
  geom_line(aes(y = randeff_spatial_only, color = "Spatial-only")) +
  geom_line(aes(y = randeff_final, color = "spatial&non-spatial"), alpha = 0.5) +
  geom_line(aes(y = randeff_nonspatial_only, color = "Non-spatial only"), alpha = 0.6) +
  labs(x = "Mb",
       y = "random effects") +
  scale_color_manual(name = "Group", 
                     values = c("realdata" = "blue", "Spatial-only" = "red", 
                                "spatial&non-spatial" = "brown", "Non-spatial only" = "green"), 
                     labels = c("obs/exp from real data", "Spatial-only", "spatial&non-spatial", "Non-spatial only")) +
  theme_minimal()


print("spatial only")

fit1 <- lm( randeff_spatial_only ~randeff + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_spatial_only)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - Spatial",
       title = "spatial only") +
  theme_minimal()

print("non-spatial only")
print(sprintf("alpha = %s",alpha_nonspatial_only))
fit1 <- lm( randeff_nonspatial_only ~randeff + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_nonspatial_only)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - non-spatial",
       title = "non-spatial only") +
  theme_minimal()


print("sptial & non-spatial ")
print(sprintf("alpha_non-spatial = %s",alpha_residual))
print("the final estimated random effects = random effects_NS * random effects_S ")


fit1 <- lm( randeff_final ~ randeff+ 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_final)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - - NS * S",
       title = "sptial & non-spatial") +
  theme_minimal()



```








### 100kb

```{r echo=F, message=FALSE, warning=FALSE, fig.width=12, fig.height=5}

load("/project/xinhe/xsun/mutation_rate/8.denovo_sns/results/sns_chr1_100kb_ssc.rdata")
data$randeff_final <- data$randeff_spatial_only * data$randeff_nonspatial_residual

ggplot(data, aes(x =  pos)) +
  geom_line(aes(y = randeff, color = "realdata"), alpha = 0.5) +
  geom_line(aes(y = randeff_spatial_only, color = "Spatial-only")) +
  geom_line(aes(y = randeff_final, color = "spatial&non-spatial"), alpha = 0.5) +
  geom_line(aes(y = randeff_nonspatial_only, color = "Non-spatial only"), alpha = 0.6) +
  labs(x = "Mb",
       y = "random effects") +
  scale_color_manual(name = "Group", 
                     values = c("realdata" = "blue", "Spatial-only" = "red", 
                                "spatial&non-spatial" = "brown", "Non-spatial only" = "green"), 
                     labels = c("obs/exp from real data", "Spatial-only", "spatial&non-spatial", "Non-spatial only")) +
  theme_minimal()


print("spatial only")

fit1 <- lm( randeff_spatial_only ~randeff + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_spatial_only)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - Spatial",
       title = "spatial only") +
  theme_minimal()

print("non-spatial only")
print(sprintf("alpha = %s",alpha_nonspatial_only))
fit1 <- lm( randeff_nonspatial_only ~randeff + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_nonspatial_only)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - non-spatial",
       title = "non-spatial only") +
  theme_minimal()


print("sptial & non-spatial ")
print(sprintf("alpha_non-spatial = %s",alpha_residual))
print("the final estimated random effects = random effects_NS * random effects_S ")


fit1 <- lm( randeff_final ~ randeff+ 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_final)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - - NS * S",
       title = "sptial & non-spatial") +
  theme_minimal()



```









## chr22 

### 10kb

```{r echo=F, message=FALSE, warning=FALSE, fig.width=12, fig.height=5}

load("/project/xinhe/xsun/mutation_rate/8.denovo_sns/results/sns_chr22_10kb_ssc.rdata")
data$randeff_final <- data$randeff_spatial_only * data$randeff_nonspatial_residual

ggplot(data, aes(x =  pos)) +
  geom_line(aes(y = randeff, color = "realdata"), alpha = 0.5) +
  geom_line(aes(y = randeff_spatial_only, color = "Spatial-only")) +
  geom_line(aes(y = randeff_final, color = "spatial&non-spatial"), alpha = 0.5) +
  geom_line(aes(y = randeff_nonspatial_only, color = "Non-spatial only"), alpha = 0.6) +
  labs(x = "Mb",
       y = "random effects") +
  scale_color_manual(name = "Group", 
                     values = c("realdata" = "blue", "Spatial-only" = "red", 
                                "spatial&non-spatial" = "brown", "Non-spatial only" = "green"), 
                     labels = c("obs/exp from real data", "Spatial-only", "spatial&non-spatial", "Non-spatial only")) +
  theme_minimal()


print("spatial only")

fit1 <- lm( randeff_spatial_only ~randeff + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_spatial_only)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - Spatial",
       title = "spatial only") +
  theme_minimal()

print("non-spatial only")
print(sprintf("alpha = %s",alpha_nonspatial_only))
fit1 <- lm( randeff_nonspatial_only ~randeff + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_nonspatial_only)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - non-spatial",
       title = "non-spatial only") +
  theme_minimal()


print("sptial & non-spatial ")
print(sprintf("alpha_non-spatial = %s",alpha_residual))
print("the final estimated random effects = random effects_NS * random effects_S ")


fit1 <- lm( randeff_final ~ randeff+ 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_final)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - - NS * S",
       title = "sptial & non-spatial") +
  theme_minimal()



```







### 30kb

```{r echo=F, message=FALSE, warning=FALSE, fig.width=12, fig.height=5}

load("/project/xinhe/xsun/mutation_rate/8.denovo_sns/results/sns_chr22_30kb_ssc.rdata")
data$randeff_final <- data$randeff_spatial_only * data$randeff_nonspatial_residual

ggplot(data, aes(x =  pos)) +
  geom_line(aes(y = randeff, color = "realdata"), alpha = 0.5) +
  geom_line(aes(y = randeff_spatial_only, color = "Spatial-only")) +
  geom_line(aes(y = randeff_final, color = "spatial&non-spatial"), alpha = 0.5) +
  geom_line(aes(y = randeff_nonspatial_only, color = "Non-spatial only"), alpha = 0.6) +
  labs(x = "Mb",
       y = "random effects") +
  scale_color_manual(name = "Group", 
                     values = c("realdata" = "blue", "Spatial-only" = "red", 
                                "spatial&non-spatial" = "brown", "Non-spatial only" = "green"), 
                     labels = c("obs/exp from real data", "Spatial-only", "spatial&non-spatial", "Non-spatial only")) +
  theme_minimal()


print("spatial only")

fit1 <- lm( randeff_spatial_only ~randeff + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_spatial_only)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - Spatial",
       title = "spatial only") +
  theme_minimal()

print("non-spatial only")
print(sprintf("alpha = %s",alpha_nonspatial_only))
fit1 <- lm( randeff_nonspatial_only ~randeff + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_nonspatial_only)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - non-spatial",
       title = "non-spatial only") +
  theme_minimal()


print("sptial & non-spatial ")
print(sprintf("alpha_non-spatial = %s",alpha_residual))
print("the final estimated random effects = random effects_NS * random effects_S ")


fit1 <- lm( randeff_final ~ randeff+ 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_final)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - - NS * S",
       title = "sptial & non-spatial") +
  theme_minimal()



```








### 50kb

```{r echo=F, message=FALSE, warning=FALSE, fig.width=12, fig.height=5}

load("/project/xinhe/xsun/mutation_rate/8.denovo_sns/results/sns_chr22_50kb_ssc.rdata")
data$randeff_final <- data$randeff_spatial_only * data$randeff_nonspatial_residual

ggplot(data, aes(x =  pos)) +
  geom_line(aes(y = randeff, color = "realdata"), alpha = 0.5) +
  geom_line(aes(y = randeff_spatial_only, color = "Spatial-only")) +
  geom_line(aes(y = randeff_final, color = "spatial&non-spatial"), alpha = 0.5) +
  geom_line(aes(y = randeff_nonspatial_only, color = "Non-spatial only"), alpha = 0.6) +
  labs(x = "Mb",
       y = "random effects") +
  scale_color_manual(name = "Group", 
                     values = c("realdata" = "blue", "Spatial-only" = "red", 
                                "spatial&non-spatial" = "brown", "Non-spatial only" = "green"), 
                     labels = c("obs/exp from real data", "Spatial-only", "spatial&non-spatial", "Non-spatial only")) +
  theme_minimal()


print("spatial only")

fit1 <- lm( randeff_spatial_only ~randeff + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_spatial_only)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - Spatial",
       title = "spatial only") +
  theme_minimal()

print("non-spatial only")
print(sprintf("alpha = %s",alpha_nonspatial_only))
fit1 <- lm( randeff_nonspatial_only ~randeff + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_nonspatial_only)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - non-spatial",
       title = "non-spatial only") +
  theme_minimal()


print("sptial & non-spatial ")
print(sprintf("alpha_non-spatial = %s",alpha_residual))
print("the final estimated random effects = random effects_NS * random effects_S ")


fit1 <- lm( randeff_final ~ randeff+ 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_final)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - - NS * S",
       title = "sptial & non-spatial") +
  theme_minimal()



```








### 100kb

```{r echo=F, message=FALSE, warning=FALSE, fig.width=12, fig.height=5}

load("/project/xinhe/xsun/mutation_rate/8.denovo_sns/results/sns_chr22_100kb_ssc.rdata")
data$randeff_final <- data$randeff_spatial_only * data$randeff_nonspatial_residual

ggplot(data, aes(x =  pos)) +
  geom_line(aes(y = randeff, color = "realdata"), alpha = 0.5) +
  geom_line(aes(y = randeff_spatial_only, color = "Spatial-only")) +
  geom_line(aes(y = randeff_final, color = "spatial&non-spatial"), alpha = 0.5) +
  geom_line(aes(y = randeff_nonspatial_only, color = "Non-spatial only"), alpha = 0.6) +
  labs(x = "Mb",
       y = "random effects") +
  scale_color_manual(name = "Group", 
                     values = c("realdata" = "blue", "Spatial-only" = "red", 
                                "spatial&non-spatial" = "brown", "Non-spatial only" = "green"), 
                     labels = c("obs/exp from real data", "Spatial-only", "spatial&non-spatial", "Non-spatial only")) +
  theme_minimal()


print("spatial only")

fit1 <- lm( randeff_spatial_only ~randeff + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_spatial_only)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - Spatial",
       title = "spatial only") +
  theme_minimal()

print("non-spatial only")
print(sprintf("alpha = %s",alpha_nonspatial_only))
fit1 <- lm( randeff_nonspatial_only ~randeff + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_nonspatial_only)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - non-spatial",
       title = "non-spatial only") +
  theme_minimal()


print("sptial & non-spatial ")
print(sprintf("alpha_non-spatial = %s",alpha_residual))
print("the final estimated random effects = random effects_NS * random effects_S ")


fit1 <- lm( randeff_final ~ randeff+ 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_final)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - - NS * S",
       title = "sptial & non-spatial") +
  theme_minimal()



```









# SSC -- cross validation

## chr1 
### 50kb

```{r echo=F, message=FALSE, warning=FALSE, fig.width=12, fig.height=5}

load("/project/xinhe/xsun/mutation_rate/8.denovo_sns/results/cv_sns_chr1_50kb_ssc.rdata")

ggplot(data, aes(x = start/1000000)) +
  geom_line(aes(y = data$count_train/data$mr_rescale_train, color = "realdata"), alpha = 0.5) +
  geom_line(aes(y = randeff_spatial_only, color = "Spatial-only")) +
  geom_line(aes(y = randeff_snons, color = "spatial&non-spatial"), alpha = 0.6) +
  geom_line(aes(y = randeff_nonspatial_only, color = "Non-spatial only"), alpha = 0.4) +
  labs(x = "Mb",
       y = "random effects") +
  scale_color_manual(name = "Group", 
                     values = c("realdata" = "blue", "Spatial-only" = "red", 
                                "spatial&non-spatial" = "brown", "Non-spatial only" = "green"), 
                     labels = c("obs/exp from real data", "Spatial-only", "spatial&non-spatial", "Non-spatial only")) +
  theme_minimal()


fit1 <- lm(mr_rescale_test ~ count_test + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = count_test, y = mr_rescale_test)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set  (RL)",
       title = "Roulette") +
  theme_minimal()

data$exp_pred_spatial <- data$mr_rescale_test*data$randeff_spatial_only

fit2 <- lm(exp_pred_spatial ~ count_test + 0, data=data)
adj_rsq2 <- summary(fit2)$adj.r.squared
ggplot(data, aes(x = count_test, y = exp_pred_spatial)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq2, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set ",
       title = "spatial only") +
  theme_minimal()


data$exp_pred_nonpatial <- data$mr_rescale_test*data$randeff_nonspatial_only

fit2 <- lm(exp_pred_nonpatial ~ count_test + 0, data=data)
adj_rsq2 <- summary(fit2)$adj.r.squared
ggplot(data, aes(x = count_test, y = exp_pred_nonpatial)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq2, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set ",
       title = "non-spatial only") +
  theme_minimal()

data$exp_pred_test_snons <- data$mr_rescale_test*data$randeff_snons
fit2 <- lm(exp_pred_test_snons ~ count_test + 0, data=data)
adj_rsq2 <- summary(fit2)$adj.r.squared
ggplot(data, aes(x = count_test, y = exp_pred_test_snons)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq2, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set (ours)",
       title = "Spatial & non-spatial") +
  theme_minimal()

```

### 100kb

```{r echo=F, message=FALSE, warning=FALSE, fig.width=12, fig.height=5}

load("/project/xinhe/xsun/mutation_rate/8.denovo_sns/results/cv_sns_chr1_100kb_ssc.rdata")

ggplot(data, aes(x = start/1000000)) +
  geom_line(aes(y = data$count_train/data$mr_rescale_train, color = "realdata"), alpha = 0.5) +
  geom_line(aes(y = randeff_spatial_only, color = "Spatial-only")) +
  geom_line(aes(y = randeff_snons, color = "spatial&non-spatial"), alpha = 0.6) +
  geom_line(aes(y = randeff_nonspatial_only, color = "Non-spatial only"), alpha = 0.4) +
  labs(x = "Mb",
       y = "random effects") +
  scale_color_manual(name = "Group", 
                     values = c("realdata" = "blue", "Spatial-only" = "red", 
                                "spatial&non-spatial" = "brown", "Non-spatial only" = "green"), 
                     labels = c("obs/exp from real data", "Spatial-only", "spatial&non-spatial", "Non-spatial only")) +
  theme_minimal()


fit1 <- lm(mr_rescale_test ~ count_test + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = count_test, y = mr_rescale_test)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set  (RL)",
       title = "Roulette") +
  theme_minimal()

data$exp_pred_spatial <- data$mr_rescale_test*data$randeff_spatial_only

fit2 <- lm(exp_pred_spatial ~ count_test + 0, data=data)
adj_rsq2 <- summary(fit2)$adj.r.squared
ggplot(data, aes(x = count_test, y = exp_pred_spatial)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq2, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set ",
       title = "spatial only") +
  theme_minimal()


data$exp_pred_nonpatial <- data$mr_rescale_test*data$randeff_nonspatial_only

fit2 <- lm(exp_pred_nonpatial ~ count_test + 0, data=data)
adj_rsq2 <- summary(fit2)$adj.r.squared
ggplot(data, aes(x = count_test, y = exp_pred_nonpatial)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq2, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set ",
       title = "non-spatial only") +
  theme_minimal()

data$exp_pred_test_snons <- data$mr_rescale_test*data$randeff_snons
fit2 <- lm(exp_pred_test_snons ~ count_test + 0, data=data)
adj_rsq2 <- summary(fit2)$adj.r.squared
ggplot(data, aes(x = count_test, y = exp_pred_test_snons)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq2, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set (ours)",
       title = "Spatial & non-spatial") +
  theme_minimal()

```


### 200kb

```{r echo=F, message=FALSE, warning=FALSE, fig.width=12, fig.height=5}

load("/project/xinhe/xsun/mutation_rate/8.denovo_sns/results/cv_sns_chr1_200kb_ssc.rdata")

ggplot(data, aes(x = start/1000000)) +
  geom_line(aes(y = data$count_train/data$mr_rescale_train, color = "realdata"), alpha = 0.5) +
  geom_line(aes(y = randeff_spatial_only, color = "Spatial-only")) +
  geom_line(aes(y = randeff_snons, color = "spatial&non-spatial"), alpha = 0.6) +
  geom_line(aes(y = randeff_nonspatial_only, color = "Non-spatial only"), alpha = 0.4) +
  labs(x = "Mb",
       y = "random effects") +
  scale_color_manual(name = "Group", 
                     values = c("realdata" = "blue", "Spatial-only" = "red", 
                                "spatial&non-spatial" = "brown", "Non-spatial only" = "green"), 
                     labels = c("obs/exp from real data", "Spatial-only", "spatial&non-spatial", "Non-spatial only")) +
  theme_minimal()


fit1 <- lm(mr_rescale_test ~ count_test + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = count_test, y = mr_rescale_test)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set  (RL)",
       title = "Roulette") +
  theme_minimal()

data$exp_pred_spatial <- data$mr_rescale_test*data$randeff_spatial_only

fit2 <- lm(exp_pred_spatial ~ count_test + 0, data=data)
adj_rsq2 <- summary(fit2)$adj.r.squared
ggplot(data, aes(x = count_test, y = exp_pred_spatial)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq2, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set ",
       title = "spatial only") +
  theme_minimal()


data$exp_pred_nonpatial <- data$mr_rescale_test*data$randeff_nonspatial_only

fit2 <- lm(exp_pred_nonpatial ~ count_test + 0, data=data)
adj_rsq2 <- summary(fit2)$adj.r.squared
ggplot(data, aes(x = count_test, y = exp_pred_nonpatial)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq2, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set ",
       title = "non-spatial only") +
  theme_minimal()

data$exp_pred_test_snons <- data$mr_rescale_test*data$randeff_snons
fit2 <- lm(exp_pred_test_snons ~ count_test + 0, data=data)
adj_rsq2 <- summary(fit2)$adj.r.squared
ggplot(data, aes(x = count_test, y = exp_pred_test_snons)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq2, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set (ours)",
       title = "Spatial & non-spatial") +
  theme_minimal()

```









## chr22

### 50kb

```{r echo=F, message=FALSE, warning=FALSE, fig.width=12, fig.height=5}

load("/project/xinhe/xsun/mutation_rate/8.denovo_sns/results/cv_sns_chr22_50kb_ssc.rdata")

ggplot(data, aes(x = start/1000000)) +
  geom_line(aes(y = data$count_train/data$mr_rescale_train, color = "realdata"), alpha = 0.5) +
  geom_line(aes(y = randeff_spatial_only, color = "Spatial-only")) +
  geom_line(aes(y = randeff_snons, color = "spatial&non-spatial"), alpha = 0.6) +
  geom_line(aes(y = randeff_nonspatial_only, color = "Non-spatial only"), alpha = 0.4) +
  labs(x = "Mb",
       y = "random effects") +
  scale_color_manual(name = "Group", 
                     values = c("realdata" = "blue", "Spatial-only" = "red", 
                                "spatial&non-spatial" = "brown", "Non-spatial only" = "green"), 
                     labels = c("obs/exp from real data", "Spatial-only", "spatial&non-spatial", "Non-spatial only")) +
  theme_minimal()


fit1 <- lm(mr_rescale_test ~ count_test + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = count_test, y = mr_rescale_test)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set  (RL)",
       title = "Roulette") +
  theme_minimal()

data$exp_pred_spatial <- data$mr_rescale_test*data$randeff_spatial_only

fit2 <- lm(exp_pred_spatial ~ count_test + 0, data=data)
adj_rsq2 <- summary(fit2)$adj.r.squared
ggplot(data, aes(x = count_test, y = exp_pred_spatial)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq2, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set ",
       title = "spatial only") +
  theme_minimal()


data$exp_pred_nonpatial <- data$mr_rescale_test*data$randeff_nonspatial_only

fit2 <- lm(exp_pred_nonpatial ~ count_test + 0, data=data)
adj_rsq2 <- summary(fit2)$adj.r.squared
ggplot(data, aes(x = count_test, y = exp_pred_nonpatial)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq2, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set ",
       title = "non-spatial only") +
  theme_minimal()

data$exp_pred_test_snons <- data$mr_rescale_test*data$randeff_snons
fit2 <- lm(exp_pred_test_snons ~ count_test + 0, data=data)
adj_rsq2 <- summary(fit2)$adj.r.squared
ggplot(data, aes(x = count_test, y = exp_pred_test_snons)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq2, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set (ours)",
       title = "Spatial & non-spatial") +
  theme_minimal()

```

### 100kb

```{r echo=F, message=FALSE, warning=FALSE, fig.width=12, fig.height=5}

load("/project/xinhe/xsun/mutation_rate/8.denovo_sns/results/cv_sns_chr22_100kb_ssc.rdata")

ggplot(data, aes(x = start/1000000)) +
  geom_line(aes(y = data$count_train/data$mr_rescale_train, color = "realdata"), alpha = 0.5) +
  geom_line(aes(y = randeff_spatial_only, color = "Spatial-only")) +
  geom_line(aes(y = randeff_snons, color = "spatial&non-spatial"), alpha = 0.6) +
  geom_line(aes(y = randeff_nonspatial_only, color = "Non-spatial only"), alpha = 0.4) +
  labs(x = "Mb",
       y = "random effects") +
  scale_color_manual(name = "Group", 
                     values = c("realdata" = "blue", "Spatial-only" = "red", 
                                "spatial&non-spatial" = "brown", "Non-spatial only" = "green"), 
                     labels = c("obs/exp from real data", "Spatial-only", "spatial&non-spatial", "Non-spatial only")) +
  theme_minimal()


fit1 <- lm(mr_rescale_test ~ count_test + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = count_test, y = mr_rescale_test)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set  (RL)",
       title = "Roulette") +
  theme_minimal()

data$exp_pred_spatial <- data$mr_rescale_test*data$randeff_spatial_only

fit2 <- lm(exp_pred_spatial ~ count_test + 0, data=data)
adj_rsq2 <- summary(fit2)$adj.r.squared
ggplot(data, aes(x = count_test, y = exp_pred_spatial)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq2, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set ",
       title = "spatial only") +
  theme_minimal()


data$exp_pred_nonpatial <- data$mr_rescale_test*data$randeff_nonspatial_only

fit2 <- lm(exp_pred_nonpatial ~ count_test + 0, data=data)
adj_rsq2 <- summary(fit2)$adj.r.squared
ggplot(data, aes(x = count_test, y = exp_pred_nonpatial)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq2, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set ",
       title = "non-spatial only") +
  theme_minimal()

data$exp_pred_test_snons <- data$mr_rescale_test*data$randeff_snons
fit2 <- lm(exp_pred_test_snons ~ count_test + 0, data=data)
adj_rsq2 <- summary(fit2)$adj.r.squared
ggplot(data, aes(x = count_test, y = exp_pred_test_snons)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq2, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set (ours)",
       title = "Spatial & non-spatial") +
  theme_minimal()

```


### 200kb

```{r echo=F, message=FALSE, warning=FALSE, fig.width=12, fig.height=5}

load("/project/xinhe/xsun/mutation_rate/8.denovo_sns/results/cv_sns_chr22_200kb_ssc.rdata")

ggplot(data, aes(x = start/1000000)) +
  geom_line(aes(y = data$count_train/data$mr_rescale_train, color = "realdata"), alpha = 0.5) +
  geom_line(aes(y = randeff_spatial_only, color = "Spatial-only")) +
  geom_line(aes(y = randeff_snons, color = "spatial&non-spatial"), alpha = 0.6) +
  geom_line(aes(y = randeff_nonspatial_only, color = "Non-spatial only"), alpha = 0.4) +
  labs(x = "Mb",
       y = "random effects") +
  scale_color_manual(name = "Group", 
                     values = c("realdata" = "blue", "Spatial-only" = "red", 
                                "spatial&non-spatial" = "brown", "Non-spatial only" = "green"), 
                     labels = c("obs/exp from real data", "Spatial-only", "spatial&non-spatial", "Non-spatial only")) +
  theme_minimal()


fit1 <- lm(mr_rescale_test ~ count_test + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = count_test, y = mr_rescale_test)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set  (RL)",
       title = "Roulette") +
  theme_minimal()

data$exp_pred_spatial <- data$mr_rescale_test*data$randeff_spatial_only

fit2 <- lm(exp_pred_spatial ~ count_test + 0, data=data)
adj_rsq2 <- summary(fit2)$adj.r.squared
ggplot(data, aes(x = count_test, y = exp_pred_spatial)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq2, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set ",
       title = "spatial only") +
  theme_minimal()


data$exp_pred_nonpatial <- data$mr_rescale_test*data$randeff_nonspatial_only

fit2 <- lm(exp_pred_nonpatial ~ count_test + 0, data=data)
adj_rsq2 <- summary(fit2)$adj.r.squared
ggplot(data, aes(x = count_test, y = exp_pred_nonpatial)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq2, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set ",
       title = "non-spatial only") +
  theme_minimal()

data$exp_pred_test_snons <- data$mr_rescale_test*data$randeff_snons
fit2 <- lm(exp_pred_test_snons ~ count_test + 0, data=data)
adj_rsq2 <- summary(fit2)$adj.r.squared
ggplot(data, aes(x = count_test, y = exp_pred_test_snons)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq2, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set (ours)",
       title = "Spatial & non-spatial") +
  theme_minimal()

```








# MSSNG -- fitting using the whole window

## chr1

### 10kb

```{r echo=F, message=FALSE, warning=FALSE, fig.width=12, fig.height=5}

load("/project/xinhe/xsun/mutation_rate/8.denovo_sns/results/sns_chr1_10kb_mssng.rdata")
data$randeff_final <- data$randeff_spatial_only * data$randeff_nonspatial_residual

ggplot(data, aes(x =  pos)) +
  geom_line(aes(y = randeff, color = "realdata"), alpha = 0.5) +
  geom_line(aes(y = randeff_spatial_only, color = "Spatial-only")) +
  geom_line(aes(y = randeff_final, color = "spatial&non-spatial"), alpha = 0.5) +
  geom_line(aes(y = randeff_nonspatial_only, color = "Non-spatial only"), alpha = 0.6) +
  labs(x = "Mb",
       y = "random effects") +
  scale_color_manual(name = "Group",
                     values = c("realdata" = "blue", "Spatial-only" = "red",
                                "spatial&non-spatial" = "brown", "Non-spatial only" = "green"),
                     labels = c("obs/exp from real data", "Spatial-only", "spatial&non-spatial", "Non-spatial only")) +
  theme_minimal()


print("spatial only")

fit1 <- lm( randeff_spatial_only ~randeff + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_spatial_only)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - Spatial",
       title = "spatial only") +
  theme_minimal()

print("non-spatial only")
print(sprintf("alpha = %s",alpha_nonspatial_only))
fit1 <- lm( randeff_nonspatial_only ~randeff + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_nonspatial_only)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - non-spatial",
       title = "non-spatial only") +
  theme_minimal()


print("sptial & non-spatial ")
print(sprintf("alpha_non-spatial = %s",alpha_residual))
print("the final estimated random effects = random effects_NS * random effects_S ")


fit1 <- lm( randeff_final ~ randeff+ 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_final)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - - NS * S",
       title = "sptial & non-spatial") +
  theme_minimal()



```







### 30kb

```{r echo=F, message=FALSE, warning=FALSE, fig.width=12, fig.height=5}

load("/project/xinhe/xsun/mutation_rate/8.denovo_sns/results/sns_chr1_30kb_mssng.rdata")
data$randeff_final <- data$randeff_spatial_only * data$randeff_nonspatial_residual

ggplot(data, aes(x =  pos)) +
  geom_line(aes(y = randeff, color = "realdata"), alpha = 0.5) +
  geom_line(aes(y = randeff_spatial_only, color = "Spatial-only")) +
  geom_line(aes(y = randeff_final, color = "spatial&non-spatial"), alpha = 0.5) +
  geom_line(aes(y = randeff_nonspatial_only, color = "Non-spatial only"), alpha = 0.6) +
  labs(x = "Mb",
       y = "random effects") +
  scale_color_manual(name = "Group",
                     values = c("realdata" = "blue", "Spatial-only" = "red",
                                "spatial&non-spatial" = "brown", "Non-spatial only" = "green"),
                     labels = c("obs/exp from real data", "Spatial-only", "spatial&non-spatial", "Non-spatial only")) +
  theme_minimal()


print("spatial only")

fit1 <- lm( randeff_spatial_only ~randeff + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_spatial_only)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - Spatial",
       title = "spatial only") +
  theme_minimal()

print("non-spatial only")
print(sprintf("alpha = %s",alpha_nonspatial_only))
fit1 <- lm( randeff_nonspatial_only ~randeff + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_nonspatial_only)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - non-spatial",
       title = "non-spatial only") +
  theme_minimal()


print("sptial & non-spatial ")
print(sprintf("alpha_non-spatial = %s",alpha_residual))
print("the final estimated random effects = random effects_NS * random effects_S ")


fit1 <- lm( randeff_final ~ randeff+ 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_final)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - - NS * S",
       title = "sptial & non-spatial") +
  theme_minimal()



```








### 50kb

```{r echo=F, message=FALSE, warning=FALSE, fig.width=12, fig.height=5}

load("/project/xinhe/xsun/mutation_rate/8.denovo_sns/results/sns_chr1_50kb_mssng.rdata")
data$randeff_final <- data$randeff_spatial_only * data$randeff_nonspatial_residual

ggplot(data, aes(x =  pos)) +
  geom_line(aes(y = randeff, color = "realdata"), alpha = 0.5) +
  geom_line(aes(y = randeff_spatial_only, color = "Spatial-only")) +
  geom_line(aes(y = randeff_final, color = "spatial&non-spatial"), alpha = 0.5) +
  geom_line(aes(y = randeff_nonspatial_only, color = "Non-spatial only"), alpha = 0.6) +
  labs(x = "Mb",
       y = "random effects") +
  scale_color_manual(name = "Group",
                     values = c("realdata" = "blue", "Spatial-only" = "red",
                                "spatial&non-spatial" = "brown", "Non-spatial only" = "green"),
                     labels = c("obs/exp from real data", "Spatial-only", "spatial&non-spatial", "Non-spatial only")) +
  theme_minimal()


print("spatial only")

fit1 <- lm( randeff_spatial_only ~randeff + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_spatial_only)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - Spatial",
       title = "spatial only") +
  theme_minimal()

print("non-spatial only")
print(sprintf("alpha = %s",alpha_nonspatial_only))
fit1 <- lm( randeff_nonspatial_only ~randeff + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_nonspatial_only)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - non-spatial",
       title = "non-spatial only") +
  theme_minimal()


print("sptial & non-spatial ")
print(sprintf("alpha_non-spatial = %s",alpha_residual))
print("the final estimated random effects = random effects_NS * random effects_S ")


fit1 <- lm( randeff_final ~ randeff+ 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_final)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - - NS * S",
       title = "sptial & non-spatial") +
  theme_minimal()



```








### 100kb

```{r echo=F, message=FALSE, warning=FALSE, fig.width=12, fig.height=5}

load("/project/xinhe/xsun/mutation_rate/8.denovo_sns/results/sns_chr1_100kb_mssng.rdata")
data$randeff_final <- data$randeff_spatial_only * data$randeff_nonspatial_residual

ggplot(data, aes(x =  pos)) +
  geom_line(aes(y = randeff, color = "realdata"), alpha = 0.5) +
  geom_line(aes(y = randeff_spatial_only, color = "Spatial-only")) +
  geom_line(aes(y = randeff_final, color = "spatial&non-spatial"), alpha = 0.5) +
  geom_line(aes(y = randeff_nonspatial_only, color = "Non-spatial only"), alpha = 0.6) +
  labs(x = "Mb",
       y = "random effects") +
  scale_color_manual(name = "Group",
                     values = c("realdata" = "blue", "Spatial-only" = "red",
                                "spatial&non-spatial" = "brown", "Non-spatial only" = "green"),
                     labels = c("obs/exp from real data", "Spatial-only", "spatial&non-spatial", "Non-spatial only")) +
  theme_minimal()


print("spatial only")

fit1 <- lm( randeff_spatial_only ~randeff + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_spatial_only)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - Spatial",
       title = "spatial only") +
  theme_minimal()

print("non-spatial only")
print(sprintf("alpha = %s",alpha_nonspatial_only))
fit1 <- lm( randeff_nonspatial_only ~randeff + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_nonspatial_only)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - non-spatial",
       title = "non-spatial only") +
  theme_minimal()


print("sptial & non-spatial ")
print(sprintf("alpha_non-spatial = %s",alpha_residual))
print("the final estimated random effects = random effects_NS * random effects_S ")


fit1 <- lm( randeff_final ~ randeff+ 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_final)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - - NS * S",
       title = "sptial & non-spatial") +
  theme_minimal()



```









## chr22

### 10kb

```{r echo=F, message=FALSE, warning=FALSE, fig.width=12, fig.height=5}

load("/project/xinhe/xsun/mutation_rate/8.denovo_sns/results/sns_chr22_10kb_mssng.rdata")
data$randeff_final <- data$randeff_spatial_only * data$randeff_nonspatial_residual

ggplot(data, aes(x =  pos)) +
  geom_line(aes(y = randeff, color = "realdata"), alpha = 0.5) +
  geom_line(aes(y = randeff_spatial_only, color = "Spatial-only")) +
  geom_line(aes(y = randeff_final, color = "spatial&non-spatial"), alpha = 0.5) +
  geom_line(aes(y = randeff_nonspatial_only, color = "Non-spatial only"), alpha = 0.6) +
  labs(x = "Mb",
       y = "random effects") +
  scale_color_manual(name = "Group",
                     values = c("realdata" = "blue", "Spatial-only" = "red",
                                "spatial&non-spatial" = "brown", "Non-spatial only" = "green"),
                     labels = c("obs/exp from real data", "Spatial-only", "spatial&non-spatial", "Non-spatial only")) +
  theme_minimal()


print("spatial only")

fit1 <- lm( randeff_spatial_only ~randeff + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_spatial_only)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - Spatial",
       title = "spatial only") +
  theme_minimal()

print("non-spatial only")
print(sprintf("alpha = %s",alpha_nonspatial_only))
fit1 <- lm( randeff_nonspatial_only ~randeff + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_nonspatial_only)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - non-spatial",
       title = "non-spatial only") +
  theme_minimal()


print("sptial & non-spatial ")
print(sprintf("alpha_non-spatial = %s",alpha_residual))
print("the final estimated random effects = random effects_NS * random effects_S ")


fit1 <- lm( randeff_final ~ randeff+ 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_final)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - - NS * S",
       title = "sptial & non-spatial") +
  theme_minimal()



```







### 30kb

```{r echo=F, message=FALSE, warning=FALSE, fig.width=12, fig.height=5}

load("/project/xinhe/xsun/mutation_rate/8.denovo_sns/results/sns_chr22_30kb_mssng.rdata")
data$randeff_final <- data$randeff_spatial_only * data$randeff_nonspatial_residual

ggplot(data, aes(x =  pos)) +
  geom_line(aes(y = randeff, color = "realdata"), alpha = 0.5) +
  geom_line(aes(y = randeff_spatial_only, color = "Spatial-only")) +
  geom_line(aes(y = randeff_final, color = "spatial&non-spatial"), alpha = 0.5) +
  geom_line(aes(y = randeff_nonspatial_only, color = "Non-spatial only"), alpha = 0.6) +
  labs(x = "Mb",
       y = "random effects") +
  scale_color_manual(name = "Group",
                     values = c("realdata" = "blue", "Spatial-only" = "red",
                                "spatial&non-spatial" = "brown", "Non-spatial only" = "green"),
                     labels = c("obs/exp from real data", "Spatial-only", "spatial&non-spatial", "Non-spatial only")) +
  theme_minimal()


print("spatial only")

fit1 <- lm( randeff_spatial_only ~randeff + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_spatial_only)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - Spatial",
       title = "spatial only") +
  theme_minimal()

print("non-spatial only")
print(sprintf("alpha = %s",alpha_nonspatial_only))
fit1 <- lm( randeff_nonspatial_only ~randeff + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_nonspatial_only)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - non-spatial",
       title = "non-spatial only") +
  theme_minimal()


print("sptial & non-spatial ")
print(sprintf("alpha_non-spatial = %s",alpha_residual))
print("the final estimated random effects = random effects_NS * random effects_S ")


fit1 <- lm( randeff_final ~ randeff+ 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_final)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - - NS * S",
       title = "sptial & non-spatial") +
  theme_minimal()



```








### 50kb

```{r echo=F, message=FALSE, warning=FALSE, fig.width=12, fig.height=5}

load("/project/xinhe/xsun/mutation_rate/8.denovo_sns/results/sns_chr22_50kb_mssng.rdata")
data$randeff_final <- data$randeff_spatial_only * data$randeff_nonspatial_residual

ggplot(data, aes(x =  pos)) +
  geom_line(aes(y = randeff, color = "realdata"), alpha = 0.5) +
  geom_line(aes(y = randeff_spatial_only, color = "Spatial-only")) +
  geom_line(aes(y = randeff_final, color = "spatial&non-spatial"), alpha = 0.5) +
  geom_line(aes(y = randeff_nonspatial_only, color = "Non-spatial only"), alpha = 0.6) +
  labs(x = "Mb",
       y = "random effects") +
  scale_color_manual(name = "Group",
                     values = c("realdata" = "blue", "Spatial-only" = "red",
                                "spatial&non-spatial" = "brown", "Non-spatial only" = "green"),
                     labels = c("obs/exp from real data", "Spatial-only", "spatial&non-spatial", "Non-spatial only")) +
  theme_minimal()


print("spatial only")

fit1 <- lm( randeff_spatial_only ~randeff + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_spatial_only)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - Spatial",
       title = "spatial only") +
  theme_minimal()

print("non-spatial only")
print(sprintf("alpha = %s",alpha_nonspatial_only))
fit1 <- lm( randeff_nonspatial_only ~randeff + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_nonspatial_only)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - non-spatial",
       title = "non-spatial only") +
  theme_minimal()


print("sptial & non-spatial ")
print(sprintf("alpha_non-spatial = %s",alpha_residual))
print("the final estimated random effects = random effects_NS * random effects_S ")


fit1 <- lm( randeff_final ~ randeff+ 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_final)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - - NS * S",
       title = "sptial & non-spatial") +
  theme_minimal()



```








### 100kb

```{r echo=F, message=FALSE, warning=FALSE, fig.width=12, fig.height=5}

load("/project/xinhe/xsun/mutation_rate/8.denovo_sns/results/sns_chr22_100kb_mssng.rdata")
data$randeff_final <- data$randeff_spatial_only * data$randeff_nonspatial_residual

ggplot(data, aes(x =  pos)) +
  geom_line(aes(y = randeff, color = "realdata"), alpha = 0.5) +
  geom_line(aes(y = randeff_spatial_only, color = "Spatial-only")) +
  geom_line(aes(y = randeff_final, color = "spatial&non-spatial"), alpha = 0.5) +
  geom_line(aes(y = randeff_nonspatial_only, color = "Non-spatial only"), alpha = 0.6) +
  labs(x = "Mb",
       y = "random effects") +
  scale_color_manual(name = "Group",
                     values = c("realdata" = "blue", "Spatial-only" = "red",
                                "spatial&non-spatial" = "brown", "Non-spatial only" = "green"),
                     labels = c("obs/exp from real data", "Spatial-only", "spatial&non-spatial", "Non-spatial only")) +
  theme_minimal()


print("spatial only")

fit1 <- lm( randeff_spatial_only ~randeff + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_spatial_only)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - Spatial",
       title = "spatial only") +
  theme_minimal()

print("non-spatial only")
print(sprintf("alpha = %s",alpha_nonspatial_only))
fit1 <- lm( randeff_nonspatial_only ~randeff + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_nonspatial_only)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - non-spatial",
       title = "non-spatial only") +
  theme_minimal()


print("sptial & non-spatial ")
print(sprintf("alpha_non-spatial = %s",alpha_residual))
print("the final estimated random effects = random effects_NS * random effects_S ")


fit1 <- lm( randeff_final ~ randeff+ 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = randeff, y = randeff_final)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "true random effect theta_i",
       y = "random effect - - NS * S",
       title = "sptial & non-spatial") +
  theme_minimal()



```









# MSSNG -- cross validation

## chr1
### 50kb

```{r echo=F, message=FALSE, warning=FALSE, fig.width=12, fig.height=5}

load("/project/xinhe/xsun/mutation_rate/8.denovo_sns/results/cv_sns_chr1_50kb_mssng.rdata")

ggplot(data, aes(x = start/1000000)) +
  geom_line(aes(y = data$count_train/data$mr_rescale_train, color = "realdata"), alpha = 0.5) +
  geom_line(aes(y = randeff_spatial_only, color = "Spatial-only")) +
  geom_line(aes(y = randeff_snons, color = "spatial&non-spatial"), alpha = 0.6) +
  geom_line(aes(y = randeff_nonspatial_only, color = "Non-spatial only"), alpha = 0.4) +
  labs(x = "Mb",
       y = "random effects") +
  scale_color_manual(name = "Group",
                     values = c("realdata" = "blue", "Spatial-only" = "red",
                                "spatial&non-spatial" = "brown", "Non-spatial only" = "green"),
                     labels = c("obs/exp from real data", "Spatial-only", "spatial&non-spatial", "Non-spatial only")) +
  theme_minimal()


fit1 <- lm(mr_rescale_test ~ count_test + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = count_test, y = mr_rescale_test)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set  (RL)",
       title = "Roulette") +
  theme_minimal()

data$exp_pred_spatial <- data$mr_rescale_test*data$randeff_spatial_only

fit2 <- lm(exp_pred_spatial ~ count_test + 0, data=data)
adj_rsq2 <- summary(fit2)$adj.r.squared
ggplot(data, aes(x = count_test, y = exp_pred_spatial)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq2, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set ",
       title = "spatial only") +
  theme_minimal()


data$exp_pred_nonpatial <- data$mr_rescale_test*data$randeff_nonspatial_only

fit2 <- lm(exp_pred_nonpatial ~ count_test + 0, data=data)
adj_rsq2 <- summary(fit2)$adj.r.squared
ggplot(data, aes(x = count_test, y = exp_pred_nonpatial)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq2, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set ",
       title = "non-spatial only") +
  theme_minimal()

data$exp_pred_test_snons <- data$mr_rescale_test*data$randeff_snons
fit2 <- lm(exp_pred_test_snons ~ count_test + 0, data=data)
adj_rsq2 <- summary(fit2)$adj.r.squared
ggplot(data, aes(x = count_test, y = exp_pred_test_snons)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq2, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set (ours)",
       title = "Spatial & non-spatial") +
  theme_minimal()

```

### 100kb

```{r echo=F, message=FALSE, warning=FALSE, fig.width=12, fig.height=5}

load("/project/xinhe/xsun/mutation_rate/8.denovo_sns/results/cv_sns_chr1_100kb_mssng.rdata")

ggplot(data, aes(x = start/1000000)) +
  geom_line(aes(y = data$count_train/data$mr_rescale_train, color = "realdata"), alpha = 0.5) +
  geom_line(aes(y = randeff_spatial_only, color = "Spatial-only")) +
  geom_line(aes(y = randeff_snons, color = "spatial&non-spatial"), alpha = 0.6) +
  geom_line(aes(y = randeff_nonspatial_only, color = "Non-spatial only"), alpha = 0.4) +
  labs(x = "Mb",
       y = "random effects") +
  scale_color_manual(name = "Group",
                     values = c("realdata" = "blue", "Spatial-only" = "red",
                                "spatial&non-spatial" = "brown", "Non-spatial only" = "green"),
                     labels = c("obs/exp from real data", "Spatial-only", "spatial&non-spatial", "Non-spatial only")) +
  theme_minimal()


fit1 <- lm(mr_rescale_test ~ count_test + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = count_test, y = mr_rescale_test)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set  (RL)",
       title = "Roulette") +
  theme_minimal()

data$exp_pred_spatial <- data$mr_rescale_test*data$randeff_spatial_only

fit2 <- lm(exp_pred_spatial ~ count_test + 0, data=data)
adj_rsq2 <- summary(fit2)$adj.r.squared
ggplot(data, aes(x = count_test, y = exp_pred_spatial)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq2, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set ",
       title = "spatial only") +
  theme_minimal()


data$exp_pred_nonpatial <- data$mr_rescale_test*data$randeff_nonspatial_only

fit2 <- lm(exp_pred_nonpatial ~ count_test + 0, data=data)
adj_rsq2 <- summary(fit2)$adj.r.squared
ggplot(data, aes(x = count_test, y = exp_pred_nonpatial)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq2, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set ",
       title = "non-spatial only") +
  theme_minimal()

data$exp_pred_test_snons <- data$mr_rescale_test*data$randeff_snons
fit2 <- lm(exp_pred_test_snons ~ count_test + 0, data=data)
adj_rsq2 <- summary(fit2)$adj.r.squared
ggplot(data, aes(x = count_test, y = exp_pred_test_snons)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq2, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set (ours)",
       title = "Spatial & non-spatial") +
  theme_minimal()

```


### 200kb

```{r echo=F, message=FALSE, warning=FALSE, fig.width=12, fig.height=5}

load("/project/xinhe/xsun/mutation_rate/8.denovo_sns/results/cv_sns_chr1_200kb_mssng.rdata")

ggplot(data, aes(x = start/1000000)) +
  geom_line(aes(y = data$count_train/data$mr_rescale_train, color = "realdata"), alpha = 0.5) +
  geom_line(aes(y = randeff_spatial_only, color = "Spatial-only")) +
  geom_line(aes(y = randeff_snons, color = "spatial&non-spatial"), alpha = 0.6) +
  geom_line(aes(y = randeff_nonspatial_only, color = "Non-spatial only"), alpha = 0.4) +
  labs(x = "Mb",
       y = "random effects") +
  scale_color_manual(name = "Group",
                     values = c("realdata" = "blue", "Spatial-only" = "red",
                                "spatial&non-spatial" = "brown", "Non-spatial only" = "green"),
                     labels = c("obs/exp from real data", "Spatial-only", "spatial&non-spatial", "Non-spatial only")) +
  theme_minimal()


fit1 <- lm(mr_rescale_test ~ count_test + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = count_test, y = mr_rescale_test)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set  (RL)",
       title = "Roulette") +
  theme_minimal()

data$exp_pred_spatial <- data$mr_rescale_test*data$randeff_spatial_only

fit2 <- lm(exp_pred_spatial ~ count_test + 0, data=data)
adj_rsq2 <- summary(fit2)$adj.r.squared
ggplot(data, aes(x = count_test, y = exp_pred_spatial)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq2, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set ",
       title = "spatial only") +
  theme_minimal()


data$exp_pred_nonpatial <- data$mr_rescale_test*data$randeff_nonspatial_only

fit2 <- lm(exp_pred_nonpatial ~ count_test + 0, data=data)
adj_rsq2 <- summary(fit2)$adj.r.squared
ggplot(data, aes(x = count_test, y = exp_pred_nonpatial)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq2, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set ",
       title = "non-spatial only") +
  theme_minimal()

data$exp_pred_test_snons <- data$mr_rescale_test*data$randeff_snons
fit2 <- lm(exp_pred_test_snons ~ count_test + 0, data=data)
adj_rsq2 <- summary(fit2)$adj.r.squared
ggplot(data, aes(x = count_test, y = exp_pred_test_snons)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq2, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set (ours)",
       title = "Spatial & non-spatial") +
  theme_minimal()

```









## chr22

### 50kb

```{r echo=F, message=FALSE, warning=FALSE, fig.width=12, fig.height=5}

load("/project/xinhe/xsun/mutation_rate/8.denovo_sns/results/cv_sns_chr22_50kb_mssng.rdata")

ggplot(data, aes(x = start/1000000)) +
  geom_line(aes(y = data$count_train/data$mr_rescale_train, color = "realdata"), alpha = 0.5) +
  geom_line(aes(y = randeff_spatial_only, color = "Spatial-only")) +
  geom_line(aes(y = randeff_snons, color = "spatial&non-spatial"), alpha = 0.6) +
  geom_line(aes(y = randeff_nonspatial_only, color = "Non-spatial only"), alpha = 0.4) +
  labs(x = "Mb",
       y = "random effects") +
  scale_color_manual(name = "Group",
                     values = c("realdata" = "blue", "Spatial-only" = "red",
                                "spatial&non-spatial" = "brown", "Non-spatial only" = "green"),
                     labels = c("obs/exp from real data", "Spatial-only", "spatial&non-spatial", "Non-spatial only")) +
  theme_minimal()


fit1 <- lm(mr_rescale_test ~ count_test + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = count_test, y = mr_rescale_test)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set  (RL)",
       title = "Roulette") +
  theme_minimal()

data$exp_pred_spatial <- data$mr_rescale_test*data$randeff_spatial_only

fit2 <- lm(exp_pred_spatial ~ count_test + 0, data=data)
adj_rsq2 <- summary(fit2)$adj.r.squared
ggplot(data, aes(x = count_test, y = exp_pred_spatial)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq2, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set ",
       title = "spatial only") +
  theme_minimal()


data$exp_pred_nonpatial <- data$mr_rescale_test*data$randeff_nonspatial_only

fit2 <- lm(exp_pred_nonpatial ~ count_test + 0, data=data)
adj_rsq2 <- summary(fit2)$adj.r.squared
ggplot(data, aes(x = count_test, y = exp_pred_nonpatial)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq2, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set ",
       title = "non-spatial only") +
  theme_minimal()

data$exp_pred_test_snons <- data$mr_rescale_test*data$randeff_snons
fit2 <- lm(exp_pred_test_snons ~ count_test + 0, data=data)
adj_rsq2 <- summary(fit2)$adj.r.squared
ggplot(data, aes(x = count_test, y = exp_pred_test_snons)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq2, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set (ours)",
       title = "Spatial & non-spatial") +
  theme_minimal()

```

### 100kb

```{r echo=F, message=FALSE, warning=FALSE, fig.width=12, fig.height=5}

load("/project/xinhe/xsun/mutation_rate/8.denovo_sns/results/cv_sns_chr22_100kb_mssng.rdata")

ggplot(data, aes(x = start/1000000)) +
  geom_line(aes(y = data$count_train/data$mr_rescale_train, color = "realdata"), alpha = 0.5) +
  geom_line(aes(y = randeff_spatial_only, color = "Spatial-only")) +
  geom_line(aes(y = randeff_snons, color = "spatial&non-spatial"), alpha = 0.6) +
  geom_line(aes(y = randeff_nonspatial_only, color = "Non-spatial only"), alpha = 0.4) +
  labs(x = "Mb",
       y = "random effects") +
  scale_color_manual(name = "Group",
                     values = c("realdata" = "blue", "Spatial-only" = "red",
                                "spatial&non-spatial" = "brown", "Non-spatial only" = "green"),
                     labels = c("obs/exp from real data", "Spatial-only", "spatial&non-spatial", "Non-spatial only")) +
  theme_minimal()


fit1 <- lm(mr_rescale_test ~ count_test + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = count_test, y = mr_rescale_test)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set  (RL)",
       title = "Roulette") +
  theme_minimal()

data$exp_pred_spatial <- data$mr_rescale_test*data$randeff_spatial_only

fit2 <- lm(exp_pred_spatial ~ count_test + 0, data=data)
adj_rsq2 <- summary(fit2)$adj.r.squared
ggplot(data, aes(x = count_test, y = exp_pred_spatial)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq2, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set ",
       title = "spatial only") +
  theme_minimal()


data$exp_pred_nonpatial <- data$mr_rescale_test*data$randeff_nonspatial_only

fit2 <- lm(exp_pred_nonpatial ~ count_test + 0, data=data)
adj_rsq2 <- summary(fit2)$adj.r.squared
ggplot(data, aes(x = count_test, y = exp_pred_nonpatial)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq2, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set ",
       title = "non-spatial only") +
  theme_minimal()

data$exp_pred_test_snons <- data$mr_rescale_test*data$randeff_snons
fit2 <- lm(exp_pred_test_snons ~ count_test + 0, data=data)
adj_rsq2 <- summary(fit2)$adj.r.squared
ggplot(data, aes(x = count_test, y = exp_pred_test_snons)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq2, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set (ours)",
       title = "Spatial & non-spatial") +
  theme_minimal()

```


### 200kb

```{r echo=F, message=FALSE, warning=FALSE, fig.width=12, fig.height=5}

load("/project/xinhe/xsun/mutation_rate/8.denovo_sns/results/cv_sns_chr22_200kb_mssng.rdata")

ggplot(data, aes(x = start/1000000)) +
  geom_line(aes(y = data$count_train/data$mr_rescale_train, color = "realdata"), alpha = 0.5) +
  geom_line(aes(y = randeff_spatial_only, color = "Spatial-only")) +
  geom_line(aes(y = randeff_snons, color = "spatial&non-spatial"), alpha = 0.6) +
  geom_line(aes(y = randeff_nonspatial_only, color = "Non-spatial only"), alpha = 0.4) +
  labs(x = "Mb",
       y = "random effects") +
  scale_color_manual(name = "Group",
                     values = c("realdata" = "blue", "Spatial-only" = "red",
                                "spatial&non-spatial" = "brown", "Non-spatial only" = "green"),
                     labels = c("obs/exp from real data", "Spatial-only", "spatial&non-spatial", "Non-spatial only")) +
  theme_minimal()


fit1 <- lm(mr_rescale_test ~ count_test + 0, data=data)
adj_rsq1 <- summary(fit1)$adj.r.squared
ggplot(data, aes(x = count_test, y = mr_rescale_test)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq1, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set  (RL)",
       title = "Roulette") +
  theme_minimal()

data$exp_pred_spatial <- data$mr_rescale_test*data$randeff_spatial_only

fit2 <- lm(exp_pred_spatial ~ count_test + 0, data=data)
adj_rsq2 <- summary(fit2)$adj.r.squared
ggplot(data, aes(x = count_test, y = exp_pred_spatial)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq2, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set ",
       title = "spatial only") +
  theme_minimal()


data$exp_pred_nonpatial <- data$mr_rescale_test*data$randeff_nonspatial_only

fit2 <- lm(exp_pred_nonpatial ~ count_test + 0, data=data)
adj_rsq2 <- summary(fit2)$adj.r.squared
ggplot(data, aes(x = count_test, y = exp_pred_nonpatial)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq2, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set ",
       title = "non-spatial only") +
  theme_minimal()

data$exp_pred_test_snons <- data$mr_rescale_test*data$randeff_snons
fit2 <- lm(exp_pred_test_snons ~ count_test + 0, data=data)
adj_rsq2 <- summary(fit2)$adj.r.squared
ggplot(data, aes(x = count_test, y = exp_pred_test_snons)) +
  geom_point(color = "black") +
  geom_abline(intercept = 0, slope = 1, color = "red") +
  geom_text(aes(label = paste("Adj R-sq =", round(adj_rsq2, 3))),
            x = Inf, y = -Inf, hjust = 1, vjust = 0,
            color = "blue") +
  labs(x = "Observed",
       y = "predicted count on testing set (ours)",
       title = "Spatial & non-spatial") +
  theme_minimal()

```











