---
title: "Comparing the # of expected SNVs and # of observed SNVs -- entire chromosome "
author: "XSun"
date: "2023-04-02"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(data.table)
```

# Data

SNV with AF < 0.001, from gnomAD v3.1 whole genome 

# CHR22

## Considerting the entire chromosome

### probability of being polymorphic -- do p = 1-exp(-mu) conversion of mutation rate to prob. of being polymorphic.

```{r echo=FALSE, message=FALSE, warning=FALSE}
merged <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/data_processed/chr22/merged_expobs_rescale_chr22.csv.gz")
merged_ac <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/data_processed/chr22/merged_expobs_rescale_chr22_ac.csv.gz")
merged_ag <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/data_processed/chr22/merged_expobs_rescale_chr22_ag.csv.gz")
merged_at <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/data_processed/chr22/merged_expobs_rescale_chr22_at.csv.gz")
merged_ca <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/data_processed/chr22/merged_expobs_rescale_chr22_ca.csv.gz")
merged_cg <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/data_processed/chr22/merged_expobs_rescale_chr22_cg.csv.gz")
merged_ct <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/data_processed/chr22/merged_expobs_rescale_chr22_ct.csv.gz")
```

- Considering the 6 mutation types collectively

```{r echo=FALSE, message=FALSE, warning=FALSE}
print(head(merged))
print(paste0("The observed number of positions that are polymorphic =", sum(!duplicated(merged[!is.na(merged$AC),]$POS))))
print(paste0("The expected number of positions that are polymorphic = ", sum(merged$p_rescale,na.rm = T)))
```

- Considering the 6 mutation types separately

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=5}
print("A-C")
print(paste0("The observed number of positions that are polymorphic = ", sum(!duplicated(merged_ac[!is.na(merged_ac$AC),]$POS)) ))
print(paste0("The expected number of positions that are polymorphic (after scaling) = ", sum(merged_ac$p_rescale,na.rm = T)))

print("A-G")
print(paste0("The observed number of positions that are polymorphic = ", sum(!duplicated(merged_ag[!is.na(merged_ag$AC),]$POS)) ))
print(paste0("The expected number of positions that are polymorphic (after scaling) = ", sum(merged_ag$p_rescale,na.rm = T)))

print("A-T")
print(paste0("The observed number of positions that are polymorphic = ", sum(!duplicated(merged_at[!is.na(merged_at$AC),]$POS)) ))
print(paste0("The expected number of positions that are polymorphic (after scaling) = ", sum(merged_at$p_rescale,na.rm = T)))

print("C-A")
print(paste0("The observed number of positions that are polymorphic = ", sum(!duplicated(merged_ca[!is.na(merged_ca$AC),]$POS)) ))
print(paste0("The expected number of positions that are polymorphic (after scaling) = ", sum(merged_ca$p_rescale,na.rm = T)))

print("C-G")
print(paste0("The observed number of positions that are polymorphic = ", sum(!duplicated(merged_cg[!is.na(merged_cg$AC),]$POS)) ))
print(paste0("The expected number of positions that are polymorphic (after scaling) = ", sum(merged_cg$p_rescale,na.rm = T)))

print("C-T")
print(paste0("The observed number of positions that are polymorphic = ", sum(!duplicated(merged_ct[!is.na(merged_ct$AC),]$POS)) ))
print(paste0("The expected number of positions that are polymorphic (after scaling) = ", sum(merged_ct$p_rescale,na.rm = T)))

observed <- c(sum(!duplicated(merged_ac[!is.na(merged_ac$AC),]$POS)),sum(!duplicated(merged_ag[!is.na(merged_ag$AC),]$POS)),sum(!duplicated(merged_at[!is.na(merged_at$AC),]$POS)),sum(!duplicated(merged_ca[!is.na(merged_ca$AC),]$POS)),sum(!duplicated(merged_cg[!is.na(merged_cg$AC),]$POS)),sum(!duplicated(merged_ct[!is.na(merged_ct$AC),]$POS)))
expected <- c(sum(merged_ac$p_rescale,na.rm = T),sum(merged_ag$p_rescale,na.rm = T),sum(merged_at$p_rescale,na.rm = T),sum(merged_ca$p_rescale,na.rm = T),sum(merged_cg$p_rescale,na.rm = T),sum(merged_ct$p_rescale,na.rm = T))

print("fitting: observed ~ expected + 0")
fit <- lm(observed ~ expected + 0)
plot(expected, observed)
abline(fit)
print(summary(fit))

```

