---
title: "Random effect modelling -- Allele Count"
author: "XSun"
date: "2023-04-04"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(data.table)
suppressMessages(library(smashr))
```

# Introduction

In this part, the chr22 was grouped into 100bp windows. We evaluate the random effects on these different windows.

# Modelling the allele count -- 1kb

## All 6 mutation types in total

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=20}
merged <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/results/chr22_grouped_1kb.bed")
colnames(merged) <- c("chr","start","end", "MR_exp","AC_obs")

print("random effect: AC_obs/AC_exp")

eff_rand <- merged$AC_obs/merged$MR_exp
eff_rand <- eff_rand[!is.na(eff_rand)]
hist(eff_rand)

plot(eff_rand)
```


## A - C

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=20}
merged <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/results/chr22_ac_1kb.bed")
colnames(merged) <- c("chr","start","end", "MR_exp","AC_obs")

print("random effect: AC_obs/AC_exp")

eff_rand <- merged$AC_obs/merged$MR_exp
eff_rand <- eff_rand[!is.na(eff_rand)]
hist(eff_rand)

plot(eff_rand)
```

## A - T

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=20}
merged <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/results/chr22_at_1kb.bed")
colnames(merged) <- c("chr","start","end", "MR_exp","AC_obs")

print("random effect: AC_obs/AC_exp")

eff_rand <- merged$AC_obs/merged$MR_exp
eff_rand <- eff_rand[!is.na(eff_rand)]
hist(eff_rand)

plot(eff_rand)
```


## A - G

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=20}
merged <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/results/chr22_ag_1kb.bed")
colnames(merged) <- c("chr","start","end", "MR_exp","AC_obs")

print("random effect: AC_obs/AC_exp")

eff_rand <- merged$AC_obs/merged$MR_exp
eff_rand <- eff_rand[!is.na(eff_rand)]
hist(eff_rand)

plot(eff_rand)
```

## C - A

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=20}
merged <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/results/chr22_ca_1kb.bed")
colnames(merged) <- c("chr","start","end", "MR_exp","AC_obs")

print("random effect: AC_obs/AC_exp")

eff_rand <- merged$AC_obs/merged$MR_exp
eff_rand <- eff_rand[!is.na(eff_rand)]
hist(eff_rand)

plot(eff_rand)
```

## C - G

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=20}
merged <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/results/chr22_ct_1kb.bed")
colnames(merged) <- c("chr","start","end", "MR_exp","AC_obs")

print("random effect: AC_obs/AC_exp")

eff_rand <- merged$AC_obs/merged$MR_exp
eff_rand <- eff_rand[!is.na(eff_rand)]
hist(eff_rand)

plot(eff_rand)
```


## C - T

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=20}
merged <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/results/chr22_ct_1kb.bed")
colnames(merged) <- c("chr","start","end", "MR_exp","AC_obs")

print("random effect: AC_obs/AC_exp")

eff_rand <- merged$AC_obs/merged$MR_exp
eff_rand <- eff_rand[!is.na(eff_rand)]
hist(eff_rand)

plot(eff_rand)
```

# Modelling the allele count -- 10kb

## All 6 mutation types in total

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=20}
merged <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/results/chr22_grouped_10kb.bed")
colnames(merged) <- c("chr","start","end", "MR_exp","AC_obs")

print("random effect: AC_obs/AC_exp")

eff_rand <- merged$AC_obs/merged$MR_exp
eff_rand <- eff_rand[!is.na(eff_rand)]
hist(eff_rand)

plot(eff_rand)

print("gauss, predicted mutation count")
mu.e2 <- smash.gaus(eff_rand)
plot(eff_rand)
lines(mu.e2,col="2")


```


## A - C

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=20}
merged <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/results/chr22_ac_10kb.bed")
colnames(merged) <- c("chr","start","end", "MR_exp","AC_obs")

print("random effect: AC_obs/AC_exp")

eff_rand <- merged$AC_obs/merged$MR_exp
eff_rand <- eff_rand[!is.na(eff_rand)]
hist(eff_rand)

plot(eff_rand)
```

## A - T

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=20}
merged <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/results/chr22_at_10kb.bed")
colnames(merged) <- c("chr","start","end", "MR_exp","AC_obs")

print("random effect: AC_obs/AC_exp")

eff_rand <- merged$AC_obs/merged$MR_exp
eff_rand <- eff_rand[!is.na(eff_rand)]
hist(eff_rand)

plot(eff_rand)
```


## A - G

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=20}
merged <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/results/chr22_ag_10kb.bed")
colnames(merged) <- c("chr","start","end", "MR_exp","AC_obs")

print("random effect: AC_obs/AC_exp")

eff_rand <- merged$AC_obs/merged$MR_exp
eff_rand <- eff_rand[!is.na(eff_rand)]
hist(eff_rand)

plot(eff_rand)
```

## C - A

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=20}
merged <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/results/chr22_ca_10kb.bed")
colnames(merged) <- c("chr","start","end", "MR_exp","AC_obs")

print("random effect: AC_obs/AC_exp")

eff_rand <- merged$AC_obs/merged$MR_exp
eff_rand <- eff_rand[!is.na(eff_rand)]
hist(eff_rand)

plot(eff_rand)
```

## C - G

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=20}
merged <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/results/chr22_ct_10kb.bed")
colnames(merged) <- c("chr","start","end", "MR_exp","AC_obs")

print("random effect: AC_obs/AC_exp")

eff_rand <- merged$AC_obs/merged$MR_exp
eff_rand <- eff_rand[!is.na(eff_rand)]
hist(eff_rand)

plot(eff_rand)
```


## C - T

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=20}
merged <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/results/chr22_ct_10kb.bed")
colnames(merged) <- c("chr","start","end", "MR_exp","AC_obs")

print("random effect: AC_obs/AC_exp")

eff_rand <- merged$AC_obs/merged$MR_exp
eff_rand <- eff_rand[!is.na(eff_rand)]
hist(eff_rand)

plot(eff_rand)
```


# Modelling the allele count -- 100bp

## All 6 mutation types in total

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=20}
merged <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/results/chr22_grouped_100bp.bed")
colnames(merged) <- c("chr","start","end", "MR_exp","AC_obs")

print("random effect: AC_obs/AC_exp")

eff_rand <- merged$AC_obs/merged$MR_exp
eff_rand <- eff_rand[!is.na(eff_rand)]
hist(eff_rand)

plot(eff_rand)
```


## A - C

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=20}
merged <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/results/chr22_ac_100bp.bed")
colnames(merged) <- c("chr","start","end", "MR_exp","AC_obs")

print("random effect: AC_obs/AC_exp")

eff_rand <- merged$AC_obs/merged$MR_exp
eff_rand <- eff_rand[!is.na(eff_rand)]
hist(eff_rand)

plot(eff_rand)
```

## A - T

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=20}
merged <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/results/chr22_at_100bp.bed")
colnames(merged) <- c("chr","start","end", "MR_exp","AC_obs")

print("random effect: AC_obs/AC_exp")

eff_rand <- merged$AC_obs/merged$MR_exp
eff_rand <- eff_rand[!is.na(eff_rand)]
hist(eff_rand)

plot(eff_rand)
```


## A - G

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=20}
merged <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/results/chr22_ag_100bp.bed")
colnames(merged) <- c("chr","start","end", "MR_exp","AC_obs")

print("random effect: AC_obs/AC_exp")

eff_rand <- merged$AC_obs/merged$MR_exp
eff_rand <- eff_rand[!is.na(eff_rand)]
hist(eff_rand)

plot(eff_rand)
```

## C - A

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=20}
merged <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/results/chr22_ca_100bp.bed")
colnames(merged) <- c("chr","start","end", "MR_exp","AC_obs")

print("random effect: AC_obs/AC_exp")

eff_rand <- merged$AC_obs/merged$MR_exp
eff_rand <- eff_rand[!is.na(eff_rand)]
hist(eff_rand)

plot(eff_rand)
```

## C - G

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=20}
merged <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/results/chr22_ct_100bp.bed")
colnames(merged) <- c("chr","start","end", "MR_exp","AC_obs")

print("random effect: AC_obs/AC_exp")

eff_rand <- merged$AC_obs/merged$MR_exp
eff_rand <- eff_rand[!is.na(eff_rand)]
hist(eff_rand)

plot(eff_rand)
```


## C - T

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=20}
merged <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/results/chr22_ct_100bp.bed")
colnames(merged) <- c("chr","start","end", "MR_exp","AC_obs")

print("random effect: AC_obs/AC_exp")

eff_rand <- merged$AC_obs/merged$MR_exp
eff_rand <- eff_rand[!is.na(eff_rand)]
hist(eff_rand)

plot(eff_rand)
```