---
title: "Cross validation for Poisson model ---- first 90% base pairs in a window as training"
author: "XSun"
date: "2023-04-20"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
suppressMessages(library(ggplot2))
suppressMessages(library(gridExtra))
```

# Introduction

We grouped the chr22 into 1kb, 10kb windows. In each window, we used the first 90% sites as training data, and the remaining 10% as the testing data. 


# 1kb

## All 6 mutation types
```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=10}

maxiter <- 30
print(paste0("iteration = ", maxiter))

file <- paste0("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/data_processed/chr22/chr22_pois_datcombine_iter",maxiter,"_1kb.rdata")
load(file)

x_max <- max(combine$SNV_exp_unsam, combine$obs_randeff_umsam)
y_max <- max(combine$SNV_obs_unsam)

fit1 <- lm(SNV_obs_unsam ~ obs_randeff_umsam + 0, data = combine)
adj.rsq <- summary(fit1)$adj.r.squared
pval <- summary(fit1)$coefficients[,4]

smash_plot <- ggplot(combine, aes(x = obs_randeff_umsam, y = SNV_obs_unsam)) +
  geom_point() +
  labs(title = "Poisson", x ="Predicted_Poisson" , y = "Observed") +
  geom_smooth(method = lm, formula = y ~ x + 0, color = "red") +
  theme_bw() +
  annotate("text", x = x_max, y = y_max, label = paste0("Adjusted R-Squared: ", round(adj.rsq, 2)), vjust = 1, hjust = 1)+
  ylim(0, y_max) +
  xlim(0, x_max) +
  theme(plot.title = element_text(hjust = 0.5))


fit2 <- lm(SNV_obs_unsam ~ SNV_exp_unsam+ 0, data = combine)
adj.rsq <- summary(fit2)$adj.r.squared
pval <- summary(fit2)$coefficients[,4]

roulette_plot <- ggplot(combine, aes(x = SNV_exp_unsam, y = SNV_obs_unsam)) +
  geom_point() +
  labs(title = "Roulette Baseline", x = "Predicted_Roulette", y = "Observed") +
  geom_smooth(method = lm, formula = y ~ x + 0, color = "red") +
  theme(plot.title = element_text(hjust = 0.5))+
  theme_bw() +
  annotate("text", x = x_max, y = y_max, label = paste0("Adjusted R-Squared: ", round(adj.rsq, 2)), vjust = 1, hjust = 1)+
  ylim(0, y_max) +
  xlim(0, x_max) +
  theme(plot.title = element_text(hjust = 0.5))

grid.arrange(smash_plot, roulette_plot, ncol = 2)

```

# 10kb

## All 6 mutation types
```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=10}

maxiter <- 30
print(paste0("iteration = ", maxiter))

file <- paste0("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/data_processed/chr22/chr22_pois_datcombine_iter",maxiter,"_10kb.rdata")
load(file)

x_max <- max(combine$SNV_exp_unsam, combine$obs_randeff_umsam)
y_max <- max(combine$SNV_obs_unsam)

fit1 <- lm(SNV_obs_unsam ~ obs_randeff_umsam + 0, data = combine)
adj.rsq <- summary(fit1)$adj.r.squared
pval <- summary(fit1)$coefficients[,4]

smash_plot <- ggplot(combine, aes(x = obs_randeff_umsam, y = SNV_obs_unsam)) +
  geom_point() +
  labs(title = "Poisson", x ="Predicted_Poisson" , y = "Observed") +
  geom_smooth(method = lm, formula = y ~ x + 0, color = "red") +
  theme_bw() +
  annotate("text", x = x_max, y = y_max, label = paste0("Adjusted R-Squared: ", round(adj.rsq, 2)), vjust = 1, hjust = 1)+
  ylim(0, y_max) +
  xlim(0, x_max) +
  theme(plot.title = element_text(hjust = 0.5))


fit2 <- lm(SNV_obs_unsam ~ SNV_exp_unsam+ 0, data = combine)
adj.rsq <- summary(fit2)$adj.r.squared
pval <- summary(fit2)$coefficients[,4]

roulette_plot <- ggplot(combine, aes(x = SNV_exp_unsam, y = SNV_obs_unsam)) +
  geom_point() +
  labs(title = "Roulette Baseline", x = "Predicted_Roulette", y = "Observed") +
  geom_smooth(method = lm, formula = y ~ x + 0, color = "red") +
  theme(plot.title = element_text(hjust = 0.5))+
  theme_bw() +
  annotate("text", x = x_max, y = y_max, label = paste0("Adjusted R-Squared: ", round(adj.rsq, 2)), vjust = 1, hjust = 1)+
  ylim(0, y_max) +
  xlim(0, x_max) +
  theme(plot.title = element_text(hjust = 0.5))

grid.arrange(smash_plot, roulette_plot, ncol = 2)

```
