---
title: "Estimating the variance using delta method"
author: "XSun"
date: "2023-04-12"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
suppressMessages(library(smashr))
suppressMessages(library(data.table))
suppressMessages(library(ggplot2))
```


# Introduction

https://www.sugarsync.com/pf/D7756315_09917662_828435

# 1kb

## All mutation types

```{r echo=T, message=FALSE, warning=FALSE,fig.height=5, fig.width=10}
data <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/data_processed/chr22/chr22.expobs.SNV.1kb.bed", fill = T)
data <- data[complete.cases(data$SNV_exp),]
data$SNV_obs[data$SNV_obs ==0] <- 0.5

data$Mb <- data$start/1000000

data$randeff <- data$SNV_obs/data$SNV_exp
data$randeff_var <- data$SNV_obs/(data$SNV_exp^2)
data$log_randeff <- log(data$randeff)

# Compute the variance of log(RE) using the delta method
g <- function(x) log(x)
g_prime <- function(x) 1/x
data$var_log_re <- (g_prime(data$randeff)^2) * data$randeff_var

ggplot(data, aes(x = Mb, y = var_log_re)) +
  geom_point(size=1) +
  labs(x = "Genomic position(MB)", y = "Variance estimated by Delta Method") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))



data$mean_lgre <- smash.gaus(data$log_randeff,sigma = data$var_log_re)
data$randeff_sm <- exp(data$mean_lgre)

ggplot(data, aes(x = Mb, y = randeff)) +
  geom_point(size=0.2) +
  geom_line(aes(x = Mb, y = randeff_sm), color = "red",size=0.2) +
  labs(x = "Genomic position(MB)", y = "Random Effect") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

```




# 10kb

## All mutation types

```{r echo=T, message=FALSE, warning=FALSE,fig.height=5, fig.width=10}
data <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/data_processed/chr22/chr22.expobs.SNV.10kb.bed", fill = T)
data <- data[complete.cases(data$SNV_exp),]
data$SNV_obs[data$SNV_obs ==0] <- 0.5

data$Mb <- data$start/1000000

data$randeff <- data$SNV_obs/data$SNV_exp
data$randeff_var <- data$SNV_obs/(data$SNV_exp^2)
data$log_randeff <- log(data$randeff)

# Compute the variance of log(RE) using the delta method
g <- function(x) log(x)
g_prime <- function(x) 1/x
data$var_log_re <- (g_prime(data$randeff)^2) * data$randeff_var

ggplot(data, aes(x = Mb, y = var_log_re)) +
  geom_point(size=1) +
  labs(x = "Genomic position(MB)", y = "Variance estimated by Delta Method") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))



data$mean_lgre <- smash.gaus(data$log_randeff,sigma = data$var_log_re)
data$randeff_sm <- exp(data$mean_lgre)

ggplot(data, aes(x = Mb, y = randeff)) +
  geom_point(size=0.2) +
  geom_line(aes(x = Mb, y = randeff_sm), color = "red",size=0.2) +
  labs(x = "Genomic position(MB)", y = "Random Effect") +
  theme_bw() +
  theme(plot.title = element_text(hjust = 0.5))

```


