---
title: "Comparing the expected mutation rate and ovserved mutation counts -- random windows"
author: "XSun"
date: "2023-04-02"
output: workflowr::wflow_html
editor_options:
  chunk_output_type: console
---

```{r echo=FALSE, message=FALSE, warning=FALSE}
library(data.table)
```

# Data

SNV with AF < 0.001, from gnomAD v3.1 whole genome 

# CHR22

```{r echo=FALSE, message=FALSE, warning=FALSE}
merged <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/results/exp_merged_rare_chr22.csv")
merged_ac <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/results/exp_merged_ac_rare_chr22.csv")
merged_ag <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/results/exp_merged_ag_rare_chr22.csv")
merged_at <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/results/exp_merged_at_rare_chr22.csv")
merged_ca <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/results/exp_merged_ca_rare_chr22.csv")
merged_cg <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/results/exp_merged_cg_rare_chr22.csv")
merged_ct <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/results/exp_merged_ct_rare_chr22.csv")

mut_obs <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/data/chr22.SNV.txt")
colnames(mut_obs) <- c("CHROM","POS","ID","REF","ALT","QUAL","FILTER","AN","AC","AF")
mut_obs <- mut_obs[mut_obs$AF<0.001,]
obs_ac <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/results/obs_ac_rare_chr22.csv")
obs_ag <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/results/obs_ag_rare_chr22.csv")
obs_at <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/results/obs_at_rare_chr22.csv")
obs_ca <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/results/obs_ca_rare_chr22.csv")
obs_cg <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/results/obs_cg_rare_chr22.csv")
obs_ct <- fread("/project/xinhe/xsun/mutation_rate/1.exp_obs_gnomad/results/obs_ct_rare_chr22.csv")
```

## Considering random windows -- 1kb

### probability of being polymorphic -- do p = 1-exp(-mu) conversion of mutation rate to prob. of being polymorphic

- Considering 6 types collectively

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=5}
pos_min <- min(merged$POS)
pos_max <- max(merged$POS)

window_size <- 1000
num_windows <- 100

max_start_pos <- pos_max - window_size + 1

# randomly sample num_windows start positions
set.seed(1)
start_positions <- sample(1:max_start_pos, num_windows, replace = FALSE)
windows <- matrix(nrow = num_windows, ncol = 2)

for (i in 1:num_windows) {
  start_pos <- start_positions[i]
  end_pos <- start_pos + window_size - 1
  windows[i,] <- c(start_pos, end_pos)
}

observed <- c()
expected <- c()
for (i in 1:num_windows){
  
  dat_window_merged <- merged[merged$POS %in% c(windows[i,1]:windows[i,2]),]
  expected[i] <- sum(dat_window_merged$p,na.rm = T)
  
  dat_window_obs <- mut_obs[mut_obs$POS %in% c(windows[i,1]:windows[i,2]),]
  observed[i] <- sum(!duplicated(dat_window_obs$POS))
  
}
fit <- lm(observed ~ expected +0)
summary(fit)
plot(expected,observed)
abline(fit)
```


- A to C

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=5}
pos_min <- min(merged_at$POS)
pos_max <- max(merged_at$POS)

window_size <- 1000
num_windows <- 100

max_start_pos <- pos_max - window_size + 1

# randomly sample num_windows start positions
set.seed(1)
start_positions <- sample(1:max_start_pos, num_windows, replace = FALSE)
windows <- matrix(nrow = num_windows, ncol = 2)

for (i in 1:num_windows) {
  start_pos <- start_positions[i]
  end_pos <- start_pos + window_size - 1
  windows[i,] <- c(start_pos, end_pos)
}

observed <- c()
expected <- c()
for (i in 1:num_windows){
  
  dat_window_merged_at <- merged_at[merged_at$POS %in% c(windows[i,1]:windows[i,2]),]
  expected[i] <- sum(dat_window_merged_at$p,na.rm = T)
  
  dat_window_obs_at <- obs_at[obs_at$POS %in% c(windows[i,1]:windows[i,2]),]
  observed[i] <- sum(!duplicated(dat_window_obs_at$POS))
  
}
fit <- lm(observed ~ expected +0)
summary(fit)
plot(expected,observed)
abline(fit)
```



### Number of allele count -- add up the mutation rates

- 6 types collectively

```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=5}

pos_min <- min(merged$POS)
pos_max <- max(merged$POS)

window_size <- 1000
num_windows <- 100

max_start_pos <- pos_max - window_size + 1

# randomly sample num_windows start positions
set.seed(1)
start_positions <- sample(1:max_start_pos, num_windows, replace = FALSE)
windows <- matrix(nrow = num_windows, ncol = 2)

for (i in 1:num_windows) {
  start_pos <- start_positions[i]
  end_pos <- start_pos + window_size - 1
  windows[i,] <- c(start_pos, end_pos)
}

observed <- c()
expected <- c()
for (i in 1:num_windows){
  
  dat_window_merged <- merged[merged$POS %in% c(windows[i,1]:windows[i,2]),]
  expected[i] <- sum(dat_window_merged$MR,na.rm = T)

  observed[i] <- sum(dat_window_merged$AC,na.rm = T)
  
}
fit <- lm(observed ~ expected +0)
summary(fit)
plot(expected,observed)
abline(fit)
```


- A to T


```{r echo=FALSE, message=FALSE, warning=FALSE,fig.height=5, fig.width=5}
pos_min <- min(merged_at$POS)
pos_max <- max(merged_at$POS)

window_size <- 1000
num_windows <- 100

max_start_pos <- pos_max - window_size + 1

# randomly sample num_windows start positions
set.seed(1)
start_positions <- sample(1:max_start_pos, num_windows, replace = FALSE)
windows <- matrix(nrow = num_windows, ncol = 2)

for (i in 1:num_windows) {
  start_pos <- start_positions[i]
  end_pos <- start_pos + window_size - 1
  windows[i,] <- c(start_pos, end_pos)
}

observed <- c()
expected <- c()
for (i in 1:num_windows){
  
  dat_window_merged_at <- merged_at[merged_at$POS %in% c(windows[i,1]:windows[i,2]),]
  expected[i] <- sum(dat_window_merged_at$p,na.rm = T)
  
  observed[i] <- sum(dat_window_merged_at$AC,na.rm = T)
  
}
fit <- lm(observed ~ expected +0)
summary(fit)
plot(expected,observed)
abline(fit)
```